"""Expanded Mongolian curriculum modules for independent practice.

The base catalog remains intact; these modules extend it without deleting existing
course content. Every lesson follows the shared lesson contract used by Jinja.
"""


def lesson(*, lesson_id, title, outcome, task, minutes, language, unit, concept, mental_model, code, mistake, best_practice, question, answer):
    return {
        "id": lesson_id,
        "title": title,
        "outcome": outcome,
        "task": task,
        "minutes": minutes,
        "language": language,
        "unit": unit,
        "concept": concept,
        "mental_model": mental_model,
        "code": code,
        "mistake": mistake,
        "best_practice": best_practice,
        "quiz": {"question": question, "answer": answer},
    }


EXTRA_MODULES = {
    "html": [
        {
            "title": "02 · Утгатай бүтэц",
            "summary": "Semantic content ба navigation",
            "lessons": [
                lesson(
                    lesson_id="html-semantic-content",
                    title="Semantic HTML: утга нь бүтэц",
                    outcome="header, main, section, article, footer-ийг зөв нөхцөлд сонгоно.",
                    task="Блогийн хуудсыг div-ийн оронд semantic landmark-уудтай болго.",
                    minutes=22,
                    language="html",
                    unit="HTML 02",
                    concept="<p>Semantic element нь browser болон туслах технологид тухайн хэсгийн үүргийг ойлгуулдаг. <code>main</code> нь гол агуулга, <code>nav</code> нь navigation, <code>article</code> нь бие даасан нийтлэл, <code>section</code> нь сэдэвчилсэн хэсгийг илэрхийлнэ.</p>",
                    mental_model="Semantic HTML бол хайрцаг бүр дээр нэр, зориулалтын шошго нааж өгч байгаа мэт. Хүн болон browser аль хайрцаг ямар үүрэгтэйг таамаглах шаардлагагүй.",
                    code="<main>\n  <article>\n    <h1>Монгол хэлээр код суръя</h1>\n    <p>Өнөөдрийн тэмдэглэл.</p>\n  </article>\n</main>",
                    mistake="Бүх хэсгийг <code>div</code>-ээр хийхэд бүтэц харагдаж байгаа ч утга алга болдог.",
                    best_practice="Элемент сонгохдоо эхлээд тухайн хэсгийн утгыг нэрлээд, дараа нь хамгийн тохирох semantic tag-ийг сонго.",
                    question="Нэг хуудсанд гол агуулгыг илэрхийлэхэд аль element тохирох вэ?",
                    answer="main element.",
                ),
                lesson(
                    lesson_id="html-links-navigation",
                    title="Link ба navigation",
                    outcome="Холбоосын зорилго, relative URL, navigation structure-ийг зөв бичнэ.",
                    task="Сургалтын 3 page рүү хүрэх navigation үүсгэ.",
                    minutes=20,
                    language="html",
                    unit="HTML 02",
                    concept="<p>Anchor element нь хэрэглэгчийг өөр resource руу хүргэнэ. <code>href</code> нь заавал утгатай байх ёстой. Link-ийн текстийг “энд дар” гэхээс илүү очих газрын нэрээр бичвэл keyboard болон screen reader хэрэглэгчид илүү ойлгомжтой.</p>",
                    mental_model="Link бол газрын зураг дээрх нэртэй замын тэмдэг. Нэрийг нь уншаад хаашаа хүрэхийг урьдчилан ойлгож болно.",
                    code="<nav aria-label=\"Үндсэн цэс\">\n  <a href=\"/\">Нүүр</a>\n  <a href=\"/lessons.html\">Хичээлүүд</a>\n  <a href=\"/projects.html\">Projects</a>\n</nav>",
                    mistake="Бүх link дээр ижил “Дэлгэрэнгүй” текст тавих нь context-гүй үед ойлгомжгүй.",
                    best_practice="Link text нь очих хуудасны нэр, action-ийг өөрөө тайлбарладаг байг.",
                    question="Link-ийн зорилгыг аль attribute тодорхойлдог вэ?",
                    answer="href attribute.",
                ),
                lesson(
                    lesson_id="html-images-media",
                    title="Зураг ба alt text",
                    outcome="Зурагт утгатай alt, decorative зурагт хоосон alt хэрэглэнэ.",
                    task="Course card бүрт descriptive image нэмээд keyboard-аар шалга.",
                    minutes=18,
                    language="html",
                    unit="HTML 02",
                    concept="<p><code>img</code> нь өөрөө хаалтгүй element. <code>alt</code> текст нь зураг харагдахгүй үед ижил мэдээллийг өгнө. Зөвхөн гоёлын зураг бол <code>alt=\"\"</code> гэж туслах технологид алгасуулна.</p>",
                    mental_model="Alt text бол зурагнаас тусдаа бичсэн богино аудио тайлбар. Зураг харагдсан үед давхардахгүй, харагдаагүй үед утгыг нөхнө.",
                    code="<figure>\n  <img src=\"python-card.png\" alt=\"Python хичээлийн course card\">\n  <figcaption>Python-оор логик сэтгэлгээг эхлүүл.</figcaption>\n</figure>",
                    mistake="Файлын нэрийг alt болгон тавих нь хэрэглэгчид бодит утга өгдөггүй.",
                    best_practice="Зураг харагдахгүй үед хэрэглэгч юу мэдэх шаардлагатайг нэг өгүүлбэрээр бич.",
                    question="Decorative image-д ямар alt утга хэрэглэдэг вэ?",
                    answer="Хоосон alt буюу alt=\"\".",
                ),
                lesson(
                    lesson_id="html-structure-bug",
                    title="Bug Lab: heading hierarchy засах",
                    outcome="Heading level алдааг олж content hierarchy-г сэргээнэ.",
                    task="h1-ээс шууд h4 рүү үсэрсэн нийтлэлийн гарчгуудыг зас.",
                    minutes=20,
                    language="html",
                    unit="HTML 02",
                    concept="<p>Heading нь үсгийн хэмжээгээр биш, агуулгын шатлалаар сонгогдоно. Нэг page гол сэдэвтээ нэг <code>h1</code> хэрэглээд дэд сэдвүүдээ <code>h2</code>, цаашлаад <code>h3</code> гэж дараалуулна.</p>",
                    mental_model="Гарчгийн шатлал бол номын агуулгын хүснэгт. Том бүлгийг алгасаад дэд дэд бүлэг рүү орох нь уншигчийг төөрөгдүүлнэ.",
                    code="<h1>Python сурах зам</h1>\n<h2>Хувьсагч</h2>\n<h3>Нэр өгөх дүрэм</h3>",
                    mistake="Гарчгийг зөвхөн том харагдуулахын тулд буруу level сонгох.",
                    best_practice="Хэмжээг CSS-ээр, утгын шатлалыг HTML heading-ээр удирд.",
                    question="Heading-ийн харагдах хэмжээг HTML level-ээр удирдах ёстой юу?",
                    answer="Үгүй. Утгын шатлал HTML-д, харагдах хэмжээ CSS-д байна.",
                ),
            ],
        },
        {
            "title": "03 · Form ба хэрэглэгчийн input",
            "summary": "Label, validation, form states",
            "lessons": [
                lesson(
                    lesson_id="html-form-labels",
                    title="Form ба label холбоос",
                    outcome="Label-ийг input-тэй for/id-аар зөв холбож чадна.",
                    task="Суралцагчийн нэр, email, зорилго авдаг form бүтээ.",
                    minutes=22,
                    language="html",
                    unit="HTML 03",
                    concept="<p>Form нь хэрэглэгчийн өгөгдлийг сервер рүү явуулах бүтэц. <code>label for</code> болон input-ийн <code>id</code> ижил байвал label дээр дарахад input focus болно, screen reader хэрэглэгч юу оруулахыг ойлгоно.</p>",
                    mental_model="Label бол form талбарын нэрийн пайз, input бол бөглөх хайрцаг. Пайз хайрцагтайгаа зөв холбогдсон үед хүн хаана юу бичихээ мэднэ.",
                    code="<label for=\"email\">Имэйл</label>\n<input id=\"email\" name=\"email\" type=\"email\" required>",
                    mistake="Placeholder-ийг label-ийн оронд ашиглан талбарын нэрийг бичиж орхих.",
                    best_practice="Placeholder нэмэлт жишээ байж болно, харин label заавал харагдах/уншигдах нэр байна.",
                    question="Label input-тэй хэрхэн холбогддог вэ?",
                    answer="label-ийн for болон input-ийн id ижил байна.",
                ),
                lesson(
                    lesson_id="html-form-validation",
                    title="Native validation ба input type",
                    outcome="required, type, minlength зэрэг constraint-ийг зөв хэрэглэнэ.",
                    task="Нууц үг 8-аас доошгүй тэмдэгттэй form validation нэм.",
                    minutes=20,
                    language="html",
                    unit="HTML 03",
                    concept="<p>HTML-ийн native validation нь хамгийн эхний хамгаалалт. <code>type=\"email\"</code> email хэлбэр, <code>required</code> хоосон биш байх, <code>minlength</code> хамгийн бага уртыг browser-д мэдэгдэнэ. Гэхдээ сервер талын validation-г орлохгүй.</p>",
                    mental_model="Form constraint бол хаалга бүрийн шалган нэвтрүүлэх дүрэм. Browser эхний шалгалт хийж, backend эцсийн шийдвэр гаргана.",
                    code="<label for=\"password\">Нууц үг</label>\n<input id=\"password\" name=\"password\" type=\"password\" minlength=\"8\" required>",
                    mistake="Frontend validation байгаа тул backend дээр дахин шалгах шаардлагагүй гэж үзэх.",
                    best_practice="Client validation-ийг user experience, server validation-ийг security гэж тусад нь ойлго.",
                    question="`required` юу шалгадаг вэ?",
                    answer="Талбар хоосон үлдээгүй эсэхийг browser түвшинд шалгана.",
                ),
                lesson(
                    lesson_id="html-form-grouping",
                    title="Form-ийг ойлгомжтой бүлэглэх",
                    outcome="fieldset, legend, autocomplete, button type ашиглана.",
                    task="Profile form-ийн contact ба learning goal хэсгийг хоёр бүлэг болго.",
                    minutes=18,
                    language="html",
                    unit="HTML 03",
                    concept="<p>Олон талбарт form-д <code>fieldset</code> болон <code>legend</code> нь ижил сэдэвтэй input-уудыг бүлэглэнэ. <code>autocomplete</code> зөв утгатай байвал хэрэглэгчийн төхөөрөмж өмнөх утгыг аюулгүй санал болгож чадна.</p>",
                    mental_model="Fieldset бол нэг асуултын багцын хүрээ, legend нь тэр хүрээний асуултын нэр.",
                    code="<fieldset>\n  <legend>Суралцах зорилго</legend>\n  <label for=\"goal\">Зорилго</label>\n  <textarea id=\"goal\" name=\"goal\"></textarea>\n</fieldset>",
                    mistake="Form доторх энгийн button-ыг type заалгүй орхиж submit санаандгүй ажиллуулах.",
                    best_practice="Action-ийн зорилгыг `type=\"submit\"` эсвэл `type=\"button\"` гэж тодорхой бич.",
                    question="Олон холбоотой form field-ийг ямар element-ээр бүлэглэдэг вэ?",
                    answer="fieldset element-ээр.",
                ),
                lesson(
                    lesson_id="html-form-bug",
                    title="Bug Lab: form submit-ийн гэнэтийн reload",
                    outcome="Button type болон preventDefault-ийн үүргийг ялгана.",
                    task="Preview товч дарахад form submit хийж reload болдог bug-ийг зас.",
                    minutes=20,
                    language="html",
                    unit="HTML 03",
                    concept="<p>Form дотор type заагаагүй button ихэнхдээ submit болдог. Зөвхөн preview хийх товч бол <code>type=\"button\"</code> байх ёстой. Жинхэнэ submit дээр browser default behavior-ийг JS-ээр удирдах шаардлагатай бол <code>preventDefault()</code> хэрэглэнэ.</p>",
                    mental_model="Submit бол form-ийн “илгээх” хаалга. Preview бол өрөөн доторх гэрэл асаах товч; тэр хаалгаар гадагш гарах ёсгүй.",
                    code="<button type=\"button\" id=\"preview\">Урьдчилан харах</button>\n<button type=\"submit\">Хадгалах</button>",
                    mistake="Бүх button-ыг submit болгож form state алдагдуулах.",
                    best_practice="Button бүрийн type-ийг зорилгоор нь explicit бич.",
                    question="Preview button form submit хийхгүй байлгах хамгийн энгийн арга юу вэ?",
                    answer="type=\"button\" гэж заах.",
                ),
            ],
        },
        {
            "title": "04 · HTML бие даасан бүтээл",
            "summary": "Requirements-оос semantic page",
            "lessons": [
                lesson(
                    lesson_id="html-project-spec",
                    title="Project brief-ийг markup болгон задлах",
                    outcome="Requirement-ийг content hierarchy ба page section болгон задлана.",
                    task="Монгол хэлний workshop page-ийн content outline гарга.",
                    minutes=25,
                    language="html",
                    unit="HTML 04",
                    concept="<p>Сайн markup эхлээд code биш outline-оос эхэлнэ. User, зорилго, гол action, content section-ээ жагсаагаад дараа нь heading болон landmark-уудыг сонгоно.</p>",
                    mental_model="Барилга барихаас өмнө зураг төсөл гаргадагтай адил page-ийн content tree-г эхлээд зур.",
                    code="<main>\n  <h1>Монгол хэлний кодын workshop</h1>\n  <section aria-labelledby=\"schedule\">\n    <h2 id=\"schedule\">Хөтөлбөр</h2>\n  </section>\n</main>",
                    mistake="Design screenshot-ийг шууд дуурайж утгагүй div tree үүсгэх.",
                    best_practice="Агуулга ба хэрэглэгчийн зорилгыг түрүүлж, харагдацыг дараа нь бод.",
                    question="Page structure-г code-оос өмнө юугаар төлөвлөх вэ?",
                    answer="Content outline буюу агуулгын модоор.",
                ),
                lesson(
                    lesson_id="html-project-checklist",
                    title="Semantic page self-review",
                    outcome="HTML page-ээ structure, link, image, form checklist-ээр өөрөө шалгана.",
                    task="Өөрийн page-д 10 зүйлтэй accessibility checklist ажиллуул.",
                    minutes=20,
                    language="html",
                    unit="HTML 04",
                    concept="<p>Self-review нь publish хийхийн өмнөх чанарын хаалга. Title, lang, heading order, landmark, link purpose, alt, label, keyboard order, valid nesting, empty state-ийг шалгана.</p>",
                    mental_model="Checklist бол нислэгийн өмнөх cockpit check. Жижиг зүйлсийг алгасахгүй байхад том алдаа багасна.",
                    code="<html lang=\"mn\">\n<head><title>Workshop</title></head>\n<body><main id=\"main-content\">...</main></body>\n</html>",
                    mistake="“Browser дээр харагдаж байна” гэдгийг “хүн бүр ашиглаж чадна” гэж андуурах.",
                    best_practice="Keyboard-only болон zoom 200%-ийн богино review-г бүр project бүр дээр хий.",
                    question="HTML page-ийн хэлний тохиргоог аль attribute заадаг вэ?",
                    answer="html element-ийн lang attribute.",
                ),
                lesson(
                    lesson_id="html-project-content",
                    title="Project: Монгол event page-ийн content",
                    outcome="Event page-ийн semantic content ба CTA-г бие даан бүтээнэ.",
                    task="Event title, speaker, schedule, location, registration form бүхий page байгуул.",
                    minutes=35,
                    language="html",
                    unit="HTML 04",
                    concept="<p>Энэ project-д өмнөх semantic structure, link, media, form чадварыг нэгтгэнэ. Эхний хувилбар гоё байх албагүй; хэрэглэгч event юу болох, хэзээ хаана болох, яаж бүртгүүлэхийг ойлгох нь гол.</p>",
                    mental_model="Нэг page бол жижиг бүтээгдэхүүн: мэдээлэл өгөх, итгэл төрүүлэх, action хийх гэсэн гурван зорилготой.",
                    code="<article>\n  <header><h1>CodeCraft Meetup</h1><p>2026 оны 5-р сарын 20</p></header>\n  <section><h2>Илтгэгч</h2><p>...</p></section>\n  <a href=\"#register\">Бүртгүүлэх</a>\n</article>",
                    mistake="Project-ийн бүх content-ийг нэг урт paragraph-д хийж structure алдагдуулах.",
                    best_practice="Information scent буюу хэрэглэгч дараагийн алхмаа ойлгохуйц гарчиг, link, CTA хэрэглэ.",
                    question="Event page-ийн гол action-ийг юу тодорхой болгох вэ?",
                    answer="Утгатай CTA link/button, жишээ нь “Бүртгүүлэх”.",
                ),
                lesson(
                    lesson_id="html-project-reflection",
                    title="Project reflection: яагаад ингэж бүтээв?",
                    outcome="Markup-ийн шийдвэрээ богино README хэлбэрээр тайлбарлана.",
                    task="Semantic choice, accessibility check, дараагийн сайжруулалтаа 5 өгүүлбэрээр бич.",
                    minutes=15,
                    language="html",
                    unit="HTML 04",
                    concept="<p>Reflection нь code-оо харах өнцгийг сайжруулна. Ямар requirement биелсэн, ямар trade-off хийсэн, ямар test үлдсэнээ бичсэнээр суралцагч өөрийн шийдвэрийг давтан ойлгодог.</p>",
                    mental_model="README бол өөрийн ирээдүйн хувилбарт үлдээсэн замын зураг.",
                    code="# Project reflection\n- Гол хэрэглэгч: ...\n- Semantic шийдвэр: ...\n- Accessibility check: ...\n- Дараагийн алхам: ...",
                    mistake="Reflection-ийг зөвхөн “бүх зүйл ажилласан” гэж ерөнхий бичих.",
                    best_practice="Нэг шийдвэр, нэг нотолгоо, нэг дараагийн алхам гэсэн бүтэц хэрэглэ.",
                    question="Reflection юуг нотлох ёстой вэ?",
                    answer="Суралцагч зөвхөн code хуулсан биш, шийдвэрээ ойлгосныг.",
                ),
            ],
        },
    ],
    "css": [
        {
            "title": "02 · Box model ба spacing",
            "summary": "Size, spacing, overflow",
            "lessons": [
                lesson(
                    lesson_id="css-selectors",
                    title="Selector-оор зөв хүрэх",
                    outcome="Type, class, id, attribute selector-ийг зорилгоор нь сонгоно.",
                    task="Course card-ийн title, status, button-ыг class selector-оор style хий.",
                    minutes=20,
                    language="css",
                    unit="CSS 02",
                    concept="<p>Selector нь HTML tree дотор аль element-д rule хэрэгжихийг сонгоно. Class нь дахин ашиглахад, id нь нэг онцгой target-д, attribute selector нь шинжээр нь сонгоход тохиромжтой.</p>",
                    mental_model="Selector бол номын index-ээс “аль бүлгийн ямар мөр”-ийг хайж байгаа асуулт.",
                    code=".course-card { padding: 1rem; }\n.course-card__title { font-size: 1.25rem; }\nbutton[data-kind=\"primary\"] { background: purple; }",
                    mistake="ID selector-ийг бүх component дээр давхар ашиглаж specificity хэт өсгөх.",
                    best_practice="Reusable visual rule-д class, page-ийн ганц landmark-д id хэрэглэ.",
                    question="Дахин ашиглагдах component-д аль selector тохиромжтой вэ?",
                    answer="Class selector.",
                ),
                lesson(
                    lesson_id="css-box-sizing",
                    title="Box model-ийг тооцоолох",
                    outcome="content, padding, border, margin-ийг ялгаж нийт хэмжээг тооцно.",
                    task="Card-ийг border-box ашиглан тогтмол өргөнтэй болго.",
                    minutes=25,
                    language="css",
                    unit="CSS 02",
                    concept="<p>Default content-box үед width зөвхөн content-д хамаарч padding/border нэмэгдэнэ. <code>box-sizing: border-box</code> үед зарласан width-д content, padding, border бүгд багтдаг.</p>",
                    mental_model="Content бол өрөө, padding бол өрөөний доторх алхах зай, border бол хана, margin бол дараагийн өрөө хүртэлх коридор.",
                    code="*, *::before, *::after { box-sizing: border-box; }\n.card { width: 320px; padding: 24px; border: 1px solid #ddd; }",
                    mistake="Width 320px гэж өгсөн ч padding нэмэгдээд mobile дээр overflow болсныг анзаарахгүй байх.",
                    best_practice="Global box-sizing reset хийж, spacing-ийг тогтсон scale-ээр удирд.",
                    question="Border-box үед width юуг багтаадаг вэ?",
                    answer="Content, padding болон border-ийг багтаана.",
                ),
                lesson(
                    lesson_id="css-spacing-scale",
                    title="Spacing scale ба consistency",
                    outcome="Spacing-ийг дурын тоогоор биш системтэй scale-ээр хэрэглэнэ.",
                    task="4, 8, 16, 24, 32 гэсэн spacing token ашиглан card зохио.",
                    minutes=18,
                    language="css",
                    unit="CSS 02",
                    concept="<p>Spacing token нь олон component-ийн зайг нэг хэлээр ярьдаг болгоно. Дурын 13px, 19px, 27px олшрох тусам design system засахад хэцүү болно.</p>",
                    mental_model="Spacing scale бол хөгжмийн хэмнэл. Бүх нот дурын урттай биш, давтагдах хэмнэлтэй үед бүтээл эвтэйхэн сонсогдоно.",
                    code=":root { --space-1: 4px; --space-2: 8px; --space-3: 16px; --space-4: 24px; }\n.card { padding: var(--space-4); gap: var(--space-3); }",
                    mistake="Component бүрт өөр өөр spacing бичиж visual rhythm алдагдуулах.",
                    best_practice="Token нэрээр хэрэглэж, token-ийн утгыг нэг газраас өөрчил.",
                    question="Spacing token-ийн гол ашиг юу вэ?",
                    answer="Consistency болон төвлөрсөн өөрчлөлт хийх боломж.",
                ),
                lesson(
                    lesson_id="css-overflow-bug",
                    title="Bug Lab: mobile overflow",
                    outcome="Fixed width, long text, flex item shrink bug-ийг оношилно.",
                    task="Mobile viewport дээр хэвтээ scroll үүсгэж буй card layout-ийг зас.",
                    minutes=22,
                    language="css",
                    unit="CSS 02",
                    concept="<p>Overflow нь ихэвчлэн fixed width, урт unbroken text, flex item-ийн min-width эсвэл зурагны max-width дутуугаас гарна. Bug-ийг таахын оронд DevTools box хэмжээг шалга.</p>",
                    mental_model="Mobile дэлгэц бол нарийн хаалга. Том хайрцгийг хүчээр чихэх биш, агуулга нь багтах төлөвлөгөө хэрэгтэй.",
                    code="img { max-width: 100%; height: auto; }\n.flex-child { min-width: 0; }\n.card { width: min(100%, 420px); }",
                    mistake="`overflow-x: hidden` тавиад үндсэн layout bug-ийг нуух.",
                    best_practice="Шалтгааныг зас; overflow hidden-ийг зөвхөн зориудын clipping-д ашигла.",
                    question="Flex item дотор урт text багтаахад ямар property тусалдаг вэ?",
                    answer="min-width: 0.",
                ),
            ],
        },
        {
            "title": "03 · Layout ба responsive",
            "summary": "Flexbox, Grid, breakpoint",
            "lessons": [
                lesson(
                    lesson_id="css-flexbox",
                    title="Flexbox-ийн хоёр тэнхлэг",
                    outcome="main axis, cross axis, gap, alignment-ийг тайлбарлаж layout хийнэ.",
                    task="Navbar-ийг desktop нэг мөр, жижиг дэлгэц дээр wrap болго.",
                    minutes=25,
                    language="css",
                    unit="CSS 03",
                    concept="<p>Flexbox нэг хэмжээст layout-д хүчтэй. <code>flex-direction</code> main axis-ийг, <code>justify-content</code> main axis-ийн, <code>align-items</code> cross axis-ийн байрлалыг удирдана.</p>",
                    mental_model="Flex container бол мөрөнд жагссан сурагчид. Багш аль чиглэлд зогсох, хоорондын зай, эгнээ солихыг заана.",
                    code=".nav { display: flex; align-items: center; justify-content: space-between; gap: 16px; flex-wrap: wrap; }",
                    mistake="justify-content ба align-items-ийг дэлгэцийн дээш/хажуу гэж тогтмол цээжлэх.",
                    best_practice="Эхлээд main axis ямар чиглэлтэйг зурж байгаад property сонго.",
                    question="`justify-content` аль тэнхлэгт ажилладаг вэ?",
                    answer="Flex-ийн main axis дээр.",
                ),
                lesson(
                    lesson_id="css-grid",
                    title="CSS Grid-ээр page layout хийх",
                    outcome="Grid track, gap, minmax, auto-fit ашиглан responsive grid байгуулна.",
                    task="Course cards-ийг 3 column-оос 1 column руу уян хатан буулга.",
                    minutes=25,
                    language="css",
                    unit="CSS 03",
                    concept="<p>Grid хоёр хэмжээст layout-д тохиромжтой. <code>repeat(auto-fit, minmax(220px, 1fr))</code> нь container-ийн өргөнөөс хамаарч column-ыг автоматаар багасгана.</p>",
                    mental_model="Grid бол хотын гудамжны зураг: мөр ба багана хоёулаа урьдчилан харагдана.",
                    code=".course-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 16px; }",
                    mistake="Mobile-д тусдаа олон fixed breakpoint бичээд layout-ийг хэврэг болгох.",
                    best_practice="Эхлээд content-ийн minimum width-ийг олж, minmax-аар уян layout хий.",
                    question="Grid-д хоёр хэмжээст layout хийхэд ямар property гол вэ?",
                    answer="grid-template-columns болон grid-template-rows.",
                ),
                lesson(
                    lesson_id="css-responsive",
                    title="Mobile-first responsive design",
                    outcome="Жижиг viewport-оос эхэлж content-д тулгуурласан breakpoint сонгоно.",
                    task="375px, 768px, 1280px хэмжээнд page layout-аа шалга.",
                    minutes=22,
                    language="css",
                    unit="CSS 03",
                    concept="<p>Responsive design нь нэг fixed screen-д биш олон нөхцөлд ажиллахыг зорьдог. Mobile-first үед үндсэн CSS жижиг дэлгэцэд, media query нь илүү өргөн дэлгэцийн enhancement байна.</p>",
                    mental_model="Нэг хувцсыг бүх биед хүчээр сунгах биш, хөдөлгөөнд тохирох уян загвар оёх.",
                    code=".layout { display: block; }\n@media (min-width: 768px) { .layout { display: grid; grid-template-columns: 1fr 300px; } }",
                    mistake="Breakpoint-ийг төхөөрөмжийн нэрээр хатуу сонгох.",
                    best_practice="Content эвдэрч эхлэх мөчөөр breakpoint сонгож, бодит viewport-оор test хий.",
                    question="Mobile-first CSS-ийн үндсэн style аль viewport-д бичигддэг вэ?",
                    answer="Жижиг viewport-д; өргөн дэлгэц нь media query-гаар нэмэгдэнэ.",
                ),
                lesson(
                    lesson_id="css-responsive-bug",
                    title="Bug Lab: fixed sidebar засах",
                    outcome="Desktop fixed two-column layout mobile дээр эвдэрсэн шалтгааныг засна.",
                    task="Sidebar-ийг mobile дээр доош шилждэг болго.",
                    minutes=22,
                    language="css",
                    unit="CSS 03",
                    concept="<p>Sidebar үргэлж 300px гэж тогтоох нь нарийн дэлгэц дээр content-д зай үлдээхгүй. Mobile дээр нэг column болгоод, өргөн дэлгэц дээр grid ашиглах нь илүү тогтвортой.</p>",
                    mental_model="Нарийн замд хоёр машин зэрэгцэхгүй; нэг нь дараа нь явна. Layout нь замын өргөнд захирагдана.",
                    code=".page { display: grid; grid-template-columns: 1fr; gap: 24px; }\n@media (min-width: 900px) { .page { grid-template-columns: minmax(0, 1fr) 300px; } }",
                    mistake="`width: 300px` sidebar-ийг бүх viewport-д хэвээр үлдээх.",
                    best_practice="Grid-ийн content column-д minmax(0, 1fr) ашиглаж overflow-ийг хяна.",
                    question="Mobile дээр sidebar-г яаж layout хийх нь зөв вэ?",
                    answer="Нэг column flow-д content-ийн дараа байрлуулах.",
                ),
            ],
        },
        {
            "title": "04 · CSS project system",
            "summary": "Tokens, states, accessibility",
            "lessons": [
                lesson(
                    lesson_id="css-tokens",
                    title="Design token үүсгэх",
                    outcome="Color, type, spacing token-ийг custom property болгон зохион байгуулна.",
                    task="Course dashboard-д light/dark өнгийн token set үүсгэ.",
                    minutes=22,
                    language="css",
                    unit="CSS 04",
                    concept="<p>Custom property нь design decision-ийг нэртэй болгож төвлөрүүлнэ. Component-ууд raw hex утга биш <code>var(--color-surface)</code> зэрэг утгатай token хэрэглэнэ.</p>",
                    mental_model="Token бол агуулахын хайрцаг дээрх нэр. Өнгө өөрчлөхөд бүх component-ийг нэг бүрчлэн ухахгүй.",
                    code=":root { --color-bg: #f8f8f4; --color-ink: #16152b; --radius-card: 16px; }\n.card { color: var(--color-ink); background: var(--color-bg); border-radius: var(--radius-card); }",
                    mistake="Token нэрийг зөвхөн өнгөөр (`--purple-1`) нэрлээд хэрэглээ нь тодорхойгүй болгох.",
                    best_practice="Role-оор нэрлэ: surface, text, accent, danger, focus.",
                    question="Component raw color биш юуг ашиглах ёстой вэ?",
                    answer="Утгатай design token custom property.",
                ),
                lesson(
                    lesson_id="css-focus-states",
                    title="Focus, hover ба reduced motion",
                    outcome="Keyboard focus болон motion preference-ийг орхигдуулахгүй style хийнэ.",
                    task="Button-д visible focus ring, hover transition, reduced-motion fallback нэм.",
                    minutes=20,
                    language="css",
                    unit="CSS 04",
                    concept="<p>Hover нь mouse хэрэглэгчид, focus нь keyboard болон бусад input хэрэглэгчдэд хэрэгтэй. <code>prefers-reduced-motion</code> сонголтыг хүндэтгэх нь хөдөлгөөнөөс эвгүйцдэг хэрэглэгчдэд чухал.</p>",
                    mental_model="Focus ring бол хэрэглэгчийн одоо хаана байгааг заах тод гэрэл. Үүнийг арилгавал замын тэмдэггүй болгоно.",
                    code="button:focus-visible { outline: 3px solid #8b6cff; outline-offset: 3px; }\n@media (prefers-reduced-motion: reduce) { * { transition-duration: .01ms; } }",
                    mistake="`outline: none` тавиад оронд нь focus style өгөхгүй орхих.",
                    best_practice="Focus-ийг арилгах бол илүү тод custom focus state заавал өг.",
                    question="Keyboard хэрэглэгчийн одоогийн element-ийг юу харуулдаг вэ?",
                    answer="Visible focus state.",
                ),
                lesson(
                    lesson_id="css-project-dashboard",
                    title="Project: responsive learning dashboard",
                    outcome="Token, Grid, card, responsive, focus state-г нэг project-д нэгтгэнэ.",
                    task="Course progress, next lesson, badge гэсэн 3 хэсэгтэй dashboard бүтээ.",
                    minutes=40,
                    language="css",
                    unit="CSS 04",
                    concept="<p>Энэ project нь CSS syntax биш системийн шийдвэр шалгана. Mobile дээр эхлээд уншигдах, desktop дээр information hierarchy тодорхой, focus state харагдах ёстой.</p>",
                    mental_model="Dashboard бол хяналтын самбар: хамгийн чухал мэдээлэл эхэнд, дараагийн action тодорхой байна.",
                    code=".dashboard { display: grid; gap: var(--space-4); }\n@media (min-width: 900px) { .dashboard { grid-template-columns: 1.4fr .6fr; } }",
                    mistake="Бүх card-ийг ижил жинтэй болгож priority алдагдуулах.",
                    best_practice="Layout-аас өмнө хэрэглэгчийн хамгийн чухал асуултыг тодорхойл.",
                    question="Responsive project-ийн эхний шалгалт юу вэ?",
                    answer="Жижиг viewport дээр content, action, focus state эвдээгүй эсэх.",
                ),
                lesson(
                    lesson_id="css-project-review",
                    title="CSS project review ба refactor",
                    outcome="Duplicate rule, specificity debt, hard-coded value-г олж refactor хийнэ.",
                    task="Өөрийн dashboard CSS-ээс 3 duplicate rule устгаж token болго.",
                    minutes=25,
                    language="css",
                    unit="CSS 04",
                    concept="<p>CSS quality нь зөвхөн screenshot биш. Давхардсан rule, хэт өндөр specificity, inline style, нэргүй color, mobile override-ийг багасгавал дараагийн өөрчлөлт аюулгүй болно.</p>",
                    mental_model="Refactor бол өрөөг нураах биш, замбараагүй шүүгээнд ангиллын шошго зүүх.",
                    code="/* Before */\n.card-a { color: #6b4ce6; }\n.card-b { color: #6b4ce6; }\n/* After */\n:root { --color-accent: #6b4ce6; }\n.card { color: var(--color-accent); }",
                    mistake="Working code-ийг refactor хийх шаардлагагүй гэж үзэх.",
                    best_practice="Behavior өөрчлөхгүй жижиг commit-оор style debt цэвэрлэ.",
                    question="CSS refactor-ийн гол зорилго юу вэ?",
                    answer="Ирээдүйн өөрчлөлтийг ойлгомжтой, аюулгүй болгох.",
                ),
            ],
        },
    ],
    "javascript": [
        {
            "title": "02 · Хэлний логик ба data",
            "summary": "Function, array, object",
            "lessons": [
                lesson(
                    lesson_id="js-values-types",
                    title="Value ба type-ийг зөв унших",
                    outcome="String, number, boolean, null, undefined-ийн ялгааг жишээгээр тайлбарлана.",
                    task="Course progress data-ийн type бүрийг console-д шалга.",
                    minutes=22,
                    language="javascript",
                    unit="JS 02",
                    concept="<p>JavaScript-д value бүр type-тэй. <code>typeof</code> нь ихэнх type-ийг шалгана, харин <code>null</code>-ийн түүхэн edge case бий. Type-ийг таах биш data contract-аар тодорхойлох нь чухал.</p>",
                    mental_model="Value бол шуудангийн хайрцагт ирсэн зүйл, type бол тэр зүйлтэй ямар үйлдэл хийж болохыг заах шошго.",
                    code="const progress = 72;\nconst title = 'HTML';\nconst completed = true;\nconsole.log(typeof progress, typeof title, typeof completed);",
                    mistake="String `'72'` ба number `72`-ийг ижил гэж үзэх.",
                    best_practice="API-аас ирсэн data-г ашиглахаас өмнө type/shape-г шалга.",
                    question="`typeof 72` юу буцаах вэ?",
                    answer="\"number\".",
                ),
                lesson(
                    lesson_id="js-functions-contract",
                    title="Function contract ба return",
                    outcome="Input, output, side effect-ийг ялгаж жижиг function бичнэ.",
                    task="XP тооцох function бичээд result-ийг return хий.",
                    minutes=25,
                    language="javascript",
                    unit="JS 02",
                    concept="<p>Function бол нэртэй, дахин ашиглагдах үйлдэл. Сайн function-д оролт, гаралт тодорхой бөгөөд боломжтой бол гадна state-ийг санаандгүй өөрчлөхгүй.</p>",
                    mental_model="Function бол жижиг машин: input хийж, contract-ийн дагуу output авна.",
                    code="function awardXp(baseXp, multiplier = 1) {\n  return baseXp * multiplier;\n}\nconsole.log(awardXp(80, 2));",
                    mistake="Function дотор console.log хийчихээд caller-д утга return хийхгүй байх.",
                    best_practice="Display хийх ба value тооцох function-ийг тусад нь байлга.",
                    question="Function-ийн caller-д утга буцаах keyword юу вэ?",
                    answer="return.",
                ),
                lesson(
                    lesson_id="js-array-methods",
                    title="Array data-г боловсруулах",
                    outcome="map, filter, find ашиглан array-тай declarative ажиллана.",
                    task="Published challenges-ээс Python challenge-уудыг filter хийж title-г map хий.",
                    minutes=25,
                    language="javascript",
                    unit="JS 02",
                    concept="<p><code>map</code> бүх item-ийг өөрчилж шинэ array, <code>filter</code> нөхцөл хангасныг шинэ array, <code>find</code> эхний тохирох item-ийг олно. Эдгээр нь loop-ийг уншихад ойлгомжтой болгодог.</p>",
                    mental_model="Array method нь conveyor belt: filter хаалга нь сонгож, map будгийн машин нь item бүрийг өөрчилнө.",
                    code="const challenges = [{language: 'python', title: 'Loop'}, {language: 'css', title: 'Grid'}];\nconst pythonTitles = challenges.filter(item => item.language === 'python').map(item => item.title);",
                    mistake="filter callback-д boolean буцаахаа мартах.",
                    best_practice="Transformation бүрийн дараа data shape юу болсонг нэрлэж шалга.",
                    question="`filter` юу буцаадаг вэ?",
                    answer="Нөхцөл хангасан item-уудаас бүрдсэн шинэ array.",
                ),
                lesson(
                    lesson_id="js-object-bug",
                    title="Bug Lab: object property ба undefined",
                    outcome="Буруу property name, optional data, fallback-ийг оношилно.",
                    task="`xp_reward` ба `xp` property зөрсөнөөс card дээр undefined гардаг bug-ийг зас.",
                    minutes=22,
                    language="javascript",
                    unit="JS 02",
                    concept="<p>Object property нэр нь data contract. Нэг газар <code>xp_reward</code>, нөгөө газар <code>xp</code> гэж зөрвөл undefined гарна. Adapter эсвэл normalized shape ашиглан энэ зөрүүг нэг газарт шийд.</p>",
                    mental_model="Object бол маягт. Талбарын нэрийг өөрөөр асуувал доторх зөв мэдээлэл байсан ч олдохгүй.",
                    code="const content = { xp_reward: 80 };\nconst xp = content.xp ?? content.xp_reward ?? 0;\nconsole.log(`${xp} XP`);",
                    mistake="Undefined утгыг шууд template string-д харуулах.",
                    best_practice="API boundary дээр normalize хийж page code-ийг нэг shape-тэй байлга.",
                    question="Fallback сонгоход ямар operator тохиромжтой вэ?",
                    answer="Nullish coalescing operator `??`.",
                ),
            ],
        },
        {
            "title": "03 · DOM ба state",
            "summary": "Event, render, safe UI",
            "lessons": [
                lesson(
                    lesson_id="js-dom-query",
                    title="DOM-ийг safe өөрчлөх",
                    outcome="querySelector, textContent, classList ашиглан UI шинэчилнэ.",
                    task="Course title болон progress text-ийг button дарахад шинэчил.",
                    minutes=22,
                    language="javascript",
                    unit="JS 03",
                    concept="<p>DOM бол HTML document-ийн object representation. User-provided text-д <code>textContent</code> ашиглавал browser markup гэж тайлбарлахгүй. <code>innerHTML</code>-ийг зөвхөн trusted static template-д маш болгоомжтой хэрэглэнэ.</p>",
                    mental_model="DOM бол page-ийн удирдлагын самбар. Selector нь товчлуурын аль унтраалгыг олохыг заана.",
                    code="const title = document.querySelector('[data-title]');\nconst button = document.querySelector('[data-next]');\nbutton.addEventListener('click', () => { title.textContent = 'Дараагийн lesson'; });",
                    mistake="User data-г innerHTML-д шууд оруулж XSS эрсдэл үүсгэх.",
                    best_practice="Text-д textContent, class state-д classList, structure-д createElement хэрэглэ.",
                    question="User-provided text-ийг DOM-д аюулгүй оруулахад юу ашиглах вэ?",
                    answer="textContent.",
                ),
                lesson(
                    lesson_id="js-events",
                    title="Event ба event delegation",
                    outcome="click, input, submit event-ийг зөв сонгож delegation хэрэглэнэ.",
                    task="Challenge list-ийн нэг parent дээр click delegation хий.",
                    minutes=25,
                    language="javascript",
                    unit="JS 03",
                    concept="<p>Event bubbling ашиглан олон ижил item-д тус бүр listener нэмэхийн оронд parent дээр нэг listener тавьж болно. <code>event.target.closest()</code> нь аль item дарсныг олоход тусална.</p>",
                    mental_model="Нэг ангид хүүхэд бүрт тусдаа микрофон өгөх биш, багшийн нэг микрофоноор хэн ярьсныг таних.",
                    code="list.addEventListener('click', (event) => {\n  const card = event.target.closest('[data-challenge]');\n  if (!card) return;\n  openChallenge(card.dataset.challenge);\n});",
                    mistake="Dynamic-ээр нэмэгдсэн item-д listener ажиллахгүй байхад initial item бүрт л listener тавих.",
                    best_practice="Dynamic list-д delegation, жижиг тогтмол control-д direct listener хэрэглэ.",
                    question="Delegation listener-ийг ихэвчлэн хаана тавьдаг вэ?",
                    answer="Олон ижил dynamic child-ийг агуулсан parent дээр.",
                ),
                lesson(
                    lesson_id="js-state-render",
                    title="State ба render function",
                    outcome="Single source of truth-оос UI render хийж stale state-ийг багасгана.",
                    task="Todo list-ийн state, render, action гэсэн гурван хэсгийг салга.",
                    minutes=28,
                    language="javascript",
                    unit="JS 03",
                    concept="<p>State бол UI-г тодорхойлох өгөгдөл. Action state-ийг өөрчилнө, render шинэ state-ийг DOM-д харуулна. Нэг утгыг DOM, localStorage, variable-д зэрэг өөрчилж зөрүүлэхгүй байх нь гол.</p>",
                    mental_model="State бол тоглоомын онооны хүснэгт, render бол тэр хүснэгтийг дэлгэц дээр зурах үйлдэл.",
                    code="let state = { count: 0 };\nfunction render() { document.querySelector('[data-count]').textContent = state.count; }\ndocument.querySelector('[data-add]').addEventListener('click', () => { state = { ...state, count: state.count + 1 }; render(); });\nrender();",
                    mistake="Нэг action дээр DOM-ийг гараар олон газар өөрчилж state-ээс зөрүүлэх.",
                    best_practice="State өөрчлөгдсөний дараа render-ийг нэг замаар дуудагддаг болго.",
                    question="UI-г ямар өгөгдөл тодорхойлдог вэ?",
                    answer="Single source of truth state.",
                ),
                lesson(
                    lesson_id="js-state-bug",
                    title="Bug Lab: stale state ба duplicate listener",
                    outcome="Event listener давхар бүртгэгдэж action хоёр удаа ажиллахыг засна.",
                    task="Page refreshгүйгээр filter солиход нэг click хоёр удаа тоологддог bug-ийг оношил.",
                    minutes=25,
                    language="javascript",
                    unit="JS 03",
                    concept="<p>Render бүр дээр listener дахин нэмбэл нэг click олон callback ажиллуулна. Event wiring-ийг initialization-д нэг удаа хий, render нь зөвхөн DOM content/state class шинэчил.</p>",
                    mental_model="Нэг хаалганд өдөр бүр шинэ хонх өлгөвөл нэг дарахад олон удаа дуугарна.",
                    code="function init() {\n  button.addEventListener('click', handleClick);\n}\n// init-ийг render дотор бүү дууд\ninit();",
                    mistake="`render()` дотор `addEventListener()` хийх.",
                    best_practice="Initialize once, render many гэсэн дүрэм баримтал.",
                    question="Duplicate listener-ийн гол шалтгаан юу вэ?",
                    answer="Render/interaction бүр дээр addEventListener-ийг дахин дуудах.",
                ),
            ],
        },
        {
            "title": "04 · Async ба product interaction",
            "summary": "Fetch, states, validation",
            "lessons": [
                lesson(
                    lesson_id="js-fetch-json",
                    title="Fetch ба JSON response",
                    outcome="HTTP response status, JSON parse, error branch-ийг зөв бичнэ.",
                    task="Challenge API-г дуудаж loading, success, error гэсэн state харуул.",
                    minutes=28,
                    language="javascript",
                    unit="JS 04",
                    concept="<p><code>fetch</code> network request эхлүүлнэ. Response ирсэн нь заавал success гэсэн үг биш тул <code>response.ok</code>-г шалгана. Дараа нь body-г JSON болгоно. JSON биш HTML error page ирж болохыг үргэлж тооц.</p>",
                    mental_model="Fetch бол шуудан захиалах. Хаалга тогшсон нь захиа зөв гэсэн үг биш; status, format, агуулгыг тусад нь шалгана.",
                    code="async function loadChallenges() {\n  const response = await fetch('/api/learning/summary');\n  if (!response.ok) throw new Error('Ачаалж чадсангүй');\n  return response.json();\n}",
                    mistake="Зөвхөн `response.json()` дуудаад HTML error дээр parse crash хийх.",
                    best_practice="Нэг удаа text уншаад JSON parse хийх shared safe response helper ашигла.",
                    question="Fetch response-ийн HTTP success-ийг аль property шалгадаг вэ?",
                    answer="response.ok.",
                ),
                lesson(
                    lesson_id="js-loading-error-empty",
                    title="Loading, error, empty state",
                    outcome="Async UI-ийн гурван үндсэн төлөвийг хэрэглэгчид ойлгомжтой харуулна.",
                    task="Challenge list empty, loading, failed гэсэн message-үүдийг тусад нь үзүүл.",
                    minutes=25,
                    language="javascript",
                    unit="JS 04",
                    concept="<p>Хоосон list нь error биш. Loading нь хэрэглэгч хүлээж байгааг, empty нь одоогоор data байхгүйг, error нь дахин оролдох боломжтой асуудлыг хэлнэ. Энэ ялгаа бие даан суралцахад чухал.</p>",
                    mental_model="Ресторан дахь “гал тогоонд бэлдэж байна”, “өнөөдөр хоол дууссан”, “гал тогоо эвдэрсэн” гэдэг гурван өөр мэдээ.",
                    code="if (state.loading) show('Ачаалж байна…');\nelse if (state.error) show('Дахин оролдох');\nelse if (!state.items.length) show('Одоогоор challenge алга');\nelse renderItems(state.items);",
                    mistake="Empty state дээр error message харуулж суралцагчийг буруу чиглүүлэх.",
                    best_practice="State бүрт нэг action эсвэл next step өг.",
                    question="Empty state error-оос юугаараа ялгаатай вэ?",
                    answer="Request амжилттай боловч харуулах data байхгүй.",
                ),
                lesson(
                    lesson_id="js-form-async",
                    title="Form submit ба async validation",
                    outcome="Submit event-г удирдаж, double submit болон server error-ийг зохицуулна.",
                    task="Login form-д pending state, server error, success redirect нэм.",
                    minutes=28,
                    language="javascript",
                    unit="JS 04",
                    concept="<p>Form submit үед default reload-ийг шаардлагатай үед зогсоож, button-ийг pending болгож давхар request-ээс хамгаална. Server-ийн validation-г user-friendly message болгон буцаана.</p>",
                    mental_model="Тасалбар авахад нэг хүн нэгэн зэрэг хоёр дугаар авахгүй; request pending байх үед action-ийг түр түгжинэ.",
                    code="form.addEventListener('submit', async (event) => {\n  event.preventDefault();\n  submitButton.disabled = true;\n  try { await submitForm(new FormData(form)); }\n  finally { submitButton.disabled = false; }\n});",
                    mistake="Request дуусаагүй байхад button олон дарагдаж duplicate record үүсгэх.",
                    best_practice="Pending state болон accessible status message заавал харуул.",
                    question="Double submit-ээс хамгаалахад юу хийх вэ?",
                    answer="Request pending үед submit button-ийг disabled болгох.",
                ),
                lesson(
                    lesson_id="js-project-tracker",
                    title="Project: learning progress tracker",
                    outcome="DOM, state, fetch, error, filter interaction-ийг нэгтгэнэ.",
                    task="Lesson list, filter, completion status, retry state бүхий tracker бүтээ.",
                    minutes=45,
                    language="javascript",
                    unit="JS 04",
                    concept="<p>Энэ project нь component-ийг хуулж хийхээс илүү UI state diagram зурж, data boundary-гаа тодорхойлохыг шаарддаг. Эхлээд demo data-гаар, дараа нь API adapter-аар ажиллуул.</p>",
                    mental_model="Tracker бол суралцагчийн газрын зураг: хаана байсан, одоо хаана, дараа хаашаа явахыг харуулна.",
                    code="const state = { items: [], filter: 'all', loading: true, error: null };\nfunction visibleItems() { return state.items.filter(item => state.filter === 'all' || item.status === state.filter); }",
                    mistake="UI бүр өөрийн тусдаа data state хадгалж progress зөрүүлэх.",
                    best_practice="Нэг state model, нэг render pipeline, нэг API adapter хэрэглэ.",
                    question="Tracker project-ийн эхний design artifact юу вэ?",
                    answer="State model болон loading/success/empty/error state diagram.",
                ),
            ],
        },
    ],
    "python": [
        {
            "title": "03 · Function ба өгөгдөл",
            "summary": "Contract, collection, reuse",
            "lessons": [
                lesson(
                    lesson_id="py-functions",
                    title="Function-ийг жижиг contract болгох",
                    outcome="Parameter, return, default value ашиглан дахин ашиглах function бичнэ.",
                    task="Үнэ, тоо, татвар авч нийт дүн буцаадаг function бич.",
                    minutes=24,
                    language="python",
                    unit="UNIT 03",
                    concept="<p>Function нь нэг тодорхой зорилготой байвал test хийхэд амар. Parameter нь оролт, return нь гаралт. <code>print</code> бол хэрэглэгчид харуулах side effect; тооцооллын function-д return илүү уян.</p>",
                    mental_model="Function бол гал тогооны жор: орцоо өгвөл тодорхой үр дүн буцаана.",
                    code="def total_price(price, quantity, tax_rate=0.1):\n    subtotal = price * quantity\n    return subtotal * (1 + tax_rate)\n\nprint(total_price(1000, 2))",
                    mistake="Тооцоолсон утгаа return хийхийн оронд зөвхөн print хийх.",
                    best_practice="Function бүрийн нэр, input, output-ийг эхлээд өгүүлбэрээр бич.",
                    question="Caller-д тооцоолсон утгыг буцаах keyword юу вэ?",
                    answer="return.",
                ),
                lesson(
                    lesson_id="py-dictionaries",
                    title="Dictionary ба data model",
                    outcome="Key-value data-г уншиж, шинэчилж, аюулгүй lookup хийнэ.",
                    task="Суралцагчийн profile dictionary үүсгээд XP болон level нэм.",
                    minutes=22,
                    language="python",
                    unit="UNIT 03",
                    concept="<p>Dictionary нь нэртэй field бүхий record-д тохиромжтой. <code>get</code> ашиглавал байхгүй key-д default өгч болно. Data model-оо тогтвортой нэрлэх нь дараагийн function-уудын contract.</p>",
                    mental_model="Dictionary бол шүүгээний drawer бүр нэртэй. Index тоолох биш нэрээр нь зөв drawer-ийг нээнэ.",
                    code="student = {'name': 'Бат', 'xp': 120, 'level': 2}\nstudent['xp'] += 40\nnext_badge = student.get('next_badge', 'Эхний алхам')\nprint(student, next_badge)",
                    mistake="Байхгүй key-ийг шууд `student['email']` гэж авч KeyError гаргах.",
                    best_practice="Заавал байх field болон optional field-ийг data model дээр ялга.",
                    question="Байхгүй key-д default өгөхөд ямар method хэрэглэдэг вэ?",
                    answer="dict.get().",
                ),
                lesson(
                    lesson_id="py-comprehension",
                    title="List comprehension-ийг ойлгож хэрэглэх",
                    outcome="Энгийн transformation/filter-ийг comprehension-аар уншигдахуйц бичнэ.",
                    task="80-аас дээш оноотой lesson-уудын title list гарга.",
                    minutes=20,
                    language="python",
                    unit="UNIT 03",
                    concept="<p>List comprehension нь жижиг, тодорхой transformation-д тохирно. Хэт олон нөхцөлтэй бол энгийн for loop илүү уншигдахуйц байж болно.</p>",
                    mental_model="Олон item-ийг нэг шүүлтүүрээр оруулаад шинэ сагсанд хийж байна.",
                    code="lessons = [{'title': 'HTML', 'score': 90}, {'title': 'CSS', 'score': 65}]\npassed = [item['title'] for item in lessons if item['score'] >= 80]\nprint(passed)",
                    mistake="Comprehension дотор хэт олон side effect хийж уншихад хэцүү болгох.",
                    best_practice="Нэг comprehension нэг гол санаатай байг.",
                    question="Comprehension юуг үүсгэдэг вэ?",
                    answer="Шинэ list буюу collection.",
                ),
                lesson(
                    lesson_id="py-function-bug",
                    title="Bug Lab: return дутсан function",
                    outcome="None гарах шалтгааныг output contract-оор оношилно.",
                    task="`average()` function print хийж байгаа ч caller-д None өгдөг bug-ийг зас.",
                    minutes=22,
                    language="python",
                    unit="UNIT 03",
                    concept="<p>Function дотор return байхгүй бол Python автоматаар <code>None</code> буцаана. Дэлгэцэнд хэвлэгдсэн output болон caller-ийн авсан return value хоёр өөр зүйл.</p>",
                    mental_model="Жор уншаад хоолыг гал тогоонд харуулсан ч хайрцагт хийж өгөөгүй бол захиалагч хоосон гарна.",
                    code="def average(scores):\n    result = sum(scores) / len(scores)\n    return result\n\nvalue = average([80, 90])\nprint(value)",
                    mistake="Debug хийхдээ print гарсан тул function зөв гэж үзэх.",
                    best_practice="Test-д function-ийн return value-г assert хий.",
                    question="Return бичээгүй Python function юу буцаадаг вэ?",
                    answer="None.",
                ),
            ],
        },
        {
            "title": "04 · File, JSON ба найдвартай data",
            "summary": "Persistence, encoding, schema",
            "lessons": [
                lesson(
                    lesson_id="py-files",
                    title="File унших ба бичих",
                    outcome="with open ашиглан текст файлд аюулгүй уншиж/бичнэ.",
                    task="Daily goal-оо `notes.txt` файлд хадгалж, дараа нь унш.",
                    minutes=24,
                    language="python",
                    unit="UNIT 04",
                    concept="<p><code>with open</code> context manager нь file-ийг ажил дуусахад хаана. Encoding-ийг explicit заавал Монгол текст эвдрэх эрсдэл багасна. Read/write mode-ийг зорилгоор нь сонго.</p>",
                    mental_model="File бол програм дууссаны дараа ч үлдэх дэвтэр. Дэвтрээ нээж бичээд заавал буцааж хаана.",
                    code="from pathlib import Path\n\npath = Path('notes.txt')\npath.write_text('Өнөөдөр нэг lesson дуусгана.', encoding='utf-8')\nprint(path.read_text(encoding='utf-8'))",
                    mistake="File path, working directory хоёр өөр гэдгийг тооцохгүй байх.",
                    best_practice="Pathlib хэрэглэж path-аа тодорхой, test-д temporary directory ашигла.",
                    question="File-ийг автоматаар хаахад ямар pattern хэрэглэдэг вэ?",
                    answer="with context manager.",
                ),
                lesson(
                    lesson_id="py-json",
                    title="JSON data хадгалах",
                    outcome="Python dict/list-ийг JSON болгон serialize/deserialize хийнэ.",
                    task="Learning progress-ийг JSON файлд хадгалж буцаан ачаал.",
                    minutes=25,
                    language="python",
                    unit="UNIT 04",
                    concept="<p>JSON нь language-уудын хооронд дамжих бүтэцтэй текст format. <code>json.dump</code> бичиж, <code>json.load</code> уншина. Schema буюу ямар field заавал байхыг өөрөө тодорхойл.</p>",
                    mental_model="JSON бол өөр өөр хэлээр ярьдаг програмуудын дунд ашигладаг нийтлэг маягт.",
                    code="import json\n\nprogress = {'completed': ['html-web'], 'xp': 120}\nwith open('progress.json', 'w', encoding='utf-8') as file:\n    json.dump(progress, file, ensure_ascii=False, indent=2)",
                    mistake="Монгол үсгийг `ensure_ascii=False`-гүй бичиж уншихад эвдэрсэн харагдуулах.",
                    best_practice="JSON schema болон version field-ийг урт наслах data-д төлөвлө.",
                    question="Python object-ийг JSON файлд бичихэд ямар function хэрэглэдэг вэ?",
                    answer="json.dump().",
                ),
                lesson(
                    lesson_id="py-paths",
                    title="Path ба environment ялгаа",
                    outcome="Relative path, absolute path, current working directory-г ойлгоно.",
                    task="Project-ийн data folder-ийг pathlib-ээр найдвартай ол.",
                    minutes=20,
                    language="python",
                    unit="UNIT 04",
                    concept="<p>Relative path нь програмыг хаанаас ажиллуулснаас хамаарна. <code>Path.cwd()</code> тухайн process-ийн working directory-г, <code>__file__</code>-д суурилсан path source file-ийн байршлыг төлөөлж болно.</p>",
                    mental_model="Хотын төвөөс “зүүн тийш 2 гудамж” гэж хэлэх нь хаана байгаагаас хамаарна; бүтэн хаяг илүү найдвартай.",
                    code="from pathlib import Path\n\nPROJECT_ROOT = Path(__file__).resolve().parent\nDATA_DIR = PROJECT_ROOT / 'data'\nDATA_DIR.mkdir(exist_ok=True)",
                    mistake="Notebook, test runner, production process бүр өөр cwd-тэй байж болохыг мартах.",
                    best_practice="Data location-оо config-оор удирдаж, path-аа нэг helper-д төвлөрүүл.",
                    question="Process хаанаас ажилласныг шалгах method юу вэ?",
                    answer="Path.cwd().",
                ),
                lesson(
                    lesson_id="py-json-bug",
                    title="Bug Lab: malformed JSON ба missing file",
                    outcome="FileNotFoundError, JSONDecodeError-ийг ялгаж user-friendly recovery хийнэ.",
                    task="JSON file байхгүй үед initial state, эвдэрсэн үед backup/error message гарга.",
                    minutes=28,
                    language="python",
                    unit="UNIT 04",
                    concept="<p>File байхгүй, JSON эвдэрсэн, schema дутуу гэсэн гурван өөр асуудал. Бүгдийг <code>except Exception</code>-оор залгихын оронд тодорхой exception барьж, хэрэглэгчид дараагийн алхмыг өг.</p>",
                    mental_model="Номын сангийн ном алга, номын хуудас урагдсан, номын бүтэц буруу гэсэн гурван өөр засвар.",
                    code="import json\n\ntry:\n    with open('progress.json', encoding='utf-8') as file:\n        data = json.load(file)\nexcept FileNotFoundError:\n    data = {'completed': [], 'xp': 0}\nexcept json.JSONDecodeError as error:\n    raise ValueError('Progress JSON эвдэрсэн байна') from error",
                    mistake="Алдааг нуухын тулд бүх exception-ийг хоосон except-д барих.",
                    best_practice="Expected recovery болон unexpected failure-г тусад нь ялга.",
                    question="Буруу JSON parse хийхэд ихэвчлэн ямар exception гардаг вэ?",
                    answer="json.JSONDecodeError.",
                ),
            ],
        },
        {
            "title": "05 · Debugging ба modules",
            "summary": "Traceback, test, separation",
            "lessons": [
                lesson(
                    lesson_id="py-traceback",
                    title="Traceback-ийг мөрөөр нь унших",
                    outcome="Exception type, file, line, call stack-ийг уншиж таамаг гаргана.",
                    task="Traceback-аас эхний өөрийн code line-ийг олж root cause тэмдэглэ.",
                    minutes=22,
                    language="python",
                    unit="UNIT 05",
                    concept="<p>Traceback-ийн доод хэсэгт exception type/message, дээр талд call stack харагдана. Хамгийн сүүлийн өөрийн code line нь эхний clue боловч өмнөх буруу data-гаас үүссэн эсэхийг бас шалгана.</p>",
                    mental_model="Traceback бол ослын дараах мөр. Сүүлчийн мөр хаана мөргөлдсөнийг, өмнөх мөрүүд хэрхэн тэнд хүрснийг хэлнэ.",
                    code="def divide(total, count):\n    if count == 0:\n        raise ValueError('count нь 0 байж болохгүй')\n    return total / count\n\nprint(divide(10, 0))",
                    mistake="Error message-ийг алгасаад шууд random line өөрчлөх.",
                    best_practice="Exception type → message → өөрийн line → input data гэсэн дарааллаар шалга.",
                    question="Traceback-ийн хамгийн доод хэсэгт юу байдаг вэ?",
                    answer="Exception type болон message.",
                ),
                lesson(
                    lesson_id="py-assert-tests",
                    title="Assert-аар өөрийгөө шалгах",
                    outcome="Function contract-ийг жижиг assert test-ээр хамгаална.",
                    task="Grade function-д normal, edge, invalid гэсэн 3 assert бич.",
                    minutes=25,
                    language="python",
                    unit="UNIT 05",
                    concept="<p>Assert нь code-ийн таамгийг executable хэлбэрээр хадгална. Automated grader-ийн тестээс гадна суралцагч өөрийн function-ийг жижиг input/output хүснэгтээр шалгаж сурна.</p>",
                    mental_model="Assert бол өөртөө тавьсан “энэ дүрэм үргэлж үнэн” гэсэн шалгалт.",
                    code="def is_passing(score):\n    return score >= 60\n\nassert is_passing(80) is True\nassert is_passing(59) is False",
                    mistake="Зөвхөн нэг happy path тестлээд edge case орхих.",
                    best_practice="Normal, boundary, invalid гэсэн гурван өнцгөөр test case бод.",
                    question="Assert амжилтгүй бол юу гардаг вэ?",
                    answer="AssertionError.",
                ),
                lesson(
                    lesson_id="py-modules",
                    title="Module ба separation of concern",
                    outcome="Нэг том script-ийг зориулалтаар нь module болгон салгана.",
                    task="Tracker-ийн calculation, storage, CLI хэсгийг тусдаа module болго.",
                    minutes=28,
                    language="python",
                    unit="UNIT 05",
                    concept="<p>Module нь нэг file доторх нэршлийн орон зай. Calculation нь input/output logic, storage нь file, CLI нь user interaction гэсэн хариуцлагаар салвал өөрчлөхөд амар.</p>",
                    mental_model="Нэг хүн бүх ажлыг хийхээс илүү багийн хүн бүр өөрийн үүрэгтэй байх.",
                    code="# scoring.py\ndef level_for_xp(xp):\n    return xp // 100 + 1\n\n# main.py\nfrom scoring import level_for_xp\nprint(level_for_xp(240))",
                    mistake="Module import хийхдээ circular dependency үүсгэх.",
                    best_practice="Dependency чиглэлийг нэг тал руу урсгаж, shared model-ийг доод түвшинд байрлуул.",
                    question="Module салгалтын гол ашиг юу вэ?",
                    answer="Хариуцлагыг тусгаарлаж, дахин ашиглах болон test хийхэд амар болгоно.",
                ),
                lesson(
                    lesson_id="py-project-cli",
                    title="Project: personal learning tracker CLI",
                    outcome="Python-ийн үндсэн чадваруудаар persistence-тэй CLI project дуусгана.",
                    task="Lesson нэмэх, дуусгасан тэмдэглэх, XP харах, JSON хадгалах CLI бүтээ.",
                    minutes=50,
                    language="python",
                    unit="UNIT 05",
                    concept="<p>Capstone project-д requirement-ээ command-ууд болгон задалж, data model, storage, validation, error handling, tests, README гэсэн дарааллаар бүтээнэ. Бүхнийг нэг дор биш жижиг milestone-оор хий.</p>",
                    mental_model="Жижиг tracker бол бодит бүтээгдэхүүний prototype: user command, state, storage, feedback дөрөв нэг дор ажиллана.",
                    code="def complete_lesson(progress, lesson_id, xp=20):\n    if lesson_id not in progress['completed']:\n        progress['completed'].append(lesson_id)\n        progress['xp'] += xp\n    return progress",
                    mistake="CLI бүх logic-ийг main function-д хийж test хийхэд хэцүү болгох.",
                    best_practice="Pure calculation function, storage adapter, command handler гэж салга.",
                    question="Capstone project дууссан гэж үзэхэд code-оос гадна юу хэрэгтэй вэ?",
                    answer="README, tests, error handling болон ажиллах demo.",
                ),
            ],
        },
    ],
}
