"""Interactive learning experiences for the CodeCraft Academy MVP."""

PRACTICE_CHALLENGES = [
    {
        "id": "py-greeting",
        "course_id": "python",
        "type": "exercise",
        "difficulty": "beginner",
        "title": "Мэндчилгээний функц",
        "hook": "Нэг нэрийг гоё мэндчилгээ болгон хувирга.",
        "description": "name параметр авч, 'Сайн уу, {name}!' гэсэн текст буцаадаг greet функцийг бич.",
        "starter_code": "def greet(name):\n    # Энд шийдлээ бич\n    pass\n\nprint(greet(\"CodeCraft\"))",
        "expected_output": "Сайн уу, CodeCraft!",
        "hint": "Функцийн дотор f-string ашиглаад return хийнэ.",
        "xp": 80,
        "lesson_id": "py-start",
    },
    {
        "id": "py-score-check",
        "course_id": "python",
        "type": "bug_lab",
        "difficulty": "beginner",
        "title": "Онооны bug hunter",
        "hook": "Яагаад зөв оноо буруу ангилагдаж байна вэ?",
        "description": "Доорх кодын нөхцөлийг засаж 86 оноог B гэж хэвлүүл.",
        "starter_code": "score = 86\n\nif score >= 90:\n    grade = \"A\"\nelif score >= 80:\n    grade = \"B\"\nelse:\n    grade = \"Keep going\"\n\nprint(grade)",
        "expected_output": "B",
        "hint": "Нөхцлүүдийг дээрээс доош дарааллаар шалгадаг гэдгийг сана.",
        "xp": 70,
        "lesson_id": "py-if",
    },
    {
        "id": "html-semantic-card",
        "course_id": "html",
        "type": "exercise",
        "difficulty": "beginner",
        "title": "Semantic profile card",
        "hook": "div-үүдийг утгатай HTML бүтэц болго.",
        "description": "Нэр, товч танилцуулга, холбоос бүхий profile card үүсгэ. h2, p, a semantic tag-ууд заавал ашигла.",
        "starter_code": "<article>\n  <!-- Нэрээ энд бич -->\n  <!-- Танилцуулгаа энд бич -->\n  <!-- Portfolio холбоосоо энд нэм -->\n</article>",
        "expected_output": "<article>",
        "hint": "article дотор h2, p, a гэсэн гурван element хэрэгтэй.",
        "xp": 80,
        "lesson_id": "html-tags",
    },
    {
        "id": "css-box-model",
        "course_id": "css",
        "type": "exercise",
        "difficulty": "beginner",
        "title": "Box model лаборатори",
        "hook": "Зайг зөв удирддаг card хий.",
        "description": "Картандаа 16px padding, 1px border, 24px margin өгч box-sizing-ийг зөв тохируул.",
        "starter_code": ".card {\n  /* Энд CSS-ээ бич */\n}",
        "expected_output": "box-sizing: border-box",
        "hint": "Дотор талын зай нь padding, гадна талын зай нь margin.",
        "xp": 80,
        "lesson_id": "css-box-model",
    },
    {
        "id": "js-counter",
        "course_id": "javascript",
        "type": "exercise",
        "difficulty": "beginner",
        "title": "Click counter",
        "hook": "DOM-ийг хөдөлгөөнтэй болго.",
        "description": "Товч дарах бүрд score 1-ээр нэмэгдэж, #score-value дотор харагддаг болго.",
        "starter_code": "let score = 0;\nconst button = document.querySelector(\"#add\");\nconst output = document.querySelector(\"#score-value\");\n\nbutton.addEventListener(\"click\", () => {\n  // Энд логикоо бич\n});",
        "expected_output": "score++",
        "hint": "Эхлээд score-ийн утгыг нэмээд дараа нь output.textContent шинэчил.",
        "xp": 90,
        "lesson_id": "js-dom-p5",
    },
    {
        "id": "frontend-portfolio",
        "course_id": "javascript",
        "type": "guided_project",
        "difficulty": "intermediate",
        "title": "Interactive portfolio page",
        "hook": "Сурсан бүхнээ нэг жижиг бүтээгдэхүүн болго.",
        "description": "HTML бүтэц, CSS responsive layout, JavaScript filter ашигласан өөрийн portfolio page бүтээ.",
        "starter_code": "<!-- Өөрийн portfolio page-ээ энд эхлүүл -->",
        "expected_output": "",
        "hint": "Эхлээд гурван project card-аа HTML-ээр үүсгээд дараа нь filter нэм.",
        "xp": 250,
        "lesson_id": "js-intro",
    },
    {
        "id": "py-values",
        "course_id": "python",
        "type": "exercise",
        "difficulty": "beginner",
        "title": "Сурагчийн profile data",
        "hook": "Өгөгдөл бүрт зөв төрлийг сонго.",
        "description": "Нэр, нас, хот, сурагч эсэх, сонгосон хичээл гэсэн таван variable үүсгэж хэвлэ.",
        "starter_code": "# Өгөгдлөө энд үүсгэ\nname = \"\"\nage = 0\ncity = \"\"\nis_student = False\n\nprint(name, age, city, is_student)",
        "expected_output": "Улаанбаатар",
        "hint": "Текстийг str, насны утгыг int, тийм/үгүйг bool төрлөөр хадгал.",
        "xp": 80,
        "lesson_id": "py-values",
    },
    {
        "id": "py-list",
        "course_id": "python",
        "type": "exercise",
        "difficulty": "beginner",
        "title": "Course list manager",
        "hook": "Суралцах замаа list-ээр удирд.",
        "description": "courses list-д JavaScript нэмээд CSS-ийг хас. Эхний болон сүүлийн course-ийг хэвлэ.",
        "starter_code": "courses = [\"HTML\", \"CSS\", \"Python\"]\n# Энд өөрчлөлтөө хий\n\nprint(courses[0])\nprint(courses[-1])",
        "expected_output": "JavaScript",
        "hint": "append() нэмнэ, remove() хасна. Сүүлийн item-д -1 index ашиглаж болно.",
        "xp": 80,
        "lesson_id": "py-list",
    },
    {
        "id": "html-structure",
        "course_id": "html",
        "type": "bug_lab",
        "difficulty": "beginner",
        "title": "Вэбийн зөв бүтэц",
        "hook": "Browser ойлгохуйц document болго.",
        "description": "Доорх HTML-д дутуу хаагдсан tag-ийг олж, зөв бүтэцтэй болго.",
        "starter_code": "<!DOCTYPE html>\n<html>\n  <body>\n    <h1>Миний page</h1>\n    <p>Танилцуулга\n  </body>\n</html>",
        "expected_output": "</p>",
        "hint": "Нээсэн element бүр хаах tag-тай байх ёстой.",
        "xp": 70,
        "lesson_id": "html-web",
    },
    {
        "id": "css-color-system",
        "course_id": "css",
        "type": "exercise",
        "difficulty": "beginner",
        "title": "Design token ашигла",
        "hook": "Өнгөө нэг газар удирддаг болго.",
        "description": ":root дотор --brand өнгө зарлаад button selector дээр var(--brand) ашигла.",
        "starter_code": ":root {\n  /* Өнгөний token-оо энд зарла */\n}\n\n.button {\n  background: /* token-оо ашигла */;\n}",
        "expected_output": "var(--brand)",
        "hint": "Custom property нь -- нэрээр эхэлж, var() функцээр уншигдана.",
        "xp": 80,
        "lesson_id": "css-intro",
    },
    {
        "id": "js-dom-click",
        "course_id": "javascript",
        "type": "bug_lab",
        "difficulty": "beginner",
        "title": "DOM event засварла",
        "hook": "Товч дарахад UI өөрчлөгдөхгүй байна.",
        "description": "Event listener болон output update-ийг зөв холбож counter-ийг ажиллуул.",
        "starter_code": "let count = 0;\nconst button = document.querySelector(\"#add\");\nconst output = document.querySelector(\"#count\");\n\nbutton.addEventListener(\"click\", () => {\n  count += 1;\n  output.textContent = count;\n});",
        "expected_output": "addEventListener",
        "hint": "querySelector-ийн selector HTML дээрх id-тэй яг таарч байгаа эсэхийг шалга.",
        "xp": 90,
        "lesson_id": "js-dom-p5",
    },
    {
        "id": "py-dictionary-filter",
        "course_id": "python",
        "type": "exercise",
        "difficulty": "intermediate",
        "title": "Түвшнээр нь шүүх",
        "hook": "Өгөгдлийг гараар биш логикоор сонго.",
        "description": "Students dictionary list-ээс score нь 80-аас их сурагчдын нэрийг шинэ list-д оруул.",
        "starter_code": "students = [{\"name\": \"Anu\", \"score\": 92}, {\"name\": \"Bataa\", \"score\": 74}]\npassed = []\n# Энд filter логикоо бич\nprint(passed)",
        "expected_output": "Anu",
        "hint": "for loop дотор score >= 80 нөхцөл шалгаад name-ийг append хий.",
        "xp": 100,
        "lesson_id": "py-list",
    },
    {
        "id": "html-accessible-form",
        "course_id": "html",
        "type": "exercise",
        "difficulty": "intermediate",
        "title": "Accessible contact form",
        "hook": "Бүх хэрэглэгч ашиглаж чадах form бүтээ.",
        "description": "Email болон message input бүрт зөв label, name, required attribute нэмээд submit button үүсгэ.",
        "starter_code": "<form>\n  <!-- label + input-аа энд бич -->\n  <!-- textarea болон submit button нэм -->\n</form>",
        "expected_output": "required",
        "hint": "label-ийн for утгыг input-ийн id-тэй ижил болго.",
        "xp": 90,
        "lesson_id": "html-tags",
    },
    {
        "id": "css-flex-layout",
        "course_id": "css",
        "type": "exercise",
        "difficulty": "intermediate",
        "title": "Flex layout засварла",
        "hook": "Card-уудаа нэг мөрөнд зөв байрлуул.",
        "description": "Container дээр display:flex, gap:16px, flex-wrap:wrap ашиглаад responsive card layout хий.",
        "starter_code": ".cards {\n  /* Layout properties энд */\n}\n\n.card {\n  min-width: 220px;\n}",
        "expected_output": "display: flex",
        "hint": "Parent container layout-ийг удирддаг гэдгийг сана.",
        "xp": 100,
        "lesson_id": "css-box-model",
    },
    {
        "id": "js-array-filter",
        "course_id": "javascript",
        "type": "exercise",
        "difficulty": "intermediate",
        "title": "Array-аас challenge сонго",
        "hook": "UI filter-ийн логикийг data дээр ажиллуул.",
        "description": "Challenges array-аас difficulty нь easy бүх challenge-ийг filter() ашиглан ялга.",
        "starter_code": "const challenges = [\n  {title: \"Greeting\", difficulty: \"easy\"},\n  {title: \"Async API\", difficulty: \"hard\"}\n];\n\nconst easy = []; // filter ашигла\nconsole.log(easy.length);",
        "expected_output": "filter",
        "hint": "filter callback true буцаасан item-уудыг шинэ array болгоно.",
        "xp": 100,
        "lesson_id": "js-dom-p5",
    },
]

PROJECT_CATALOG = [
    {
        "id": "expense-tracker",
        "course_id": "python",
        "type": "portfolio_project",
        "title": "CLI Expense Tracker",
        "subtitle": "Өдөр тутмын зардлаа Python-оор удирд.",
        "description": "Function, list, dictionary, JSON file ашиглаад нэмэх, жагсаах, нийт дүн гаргах боломжтой command-line app бүтээнэ.",
        "steps": [
            "Зардлын object-ийн бүтэц тодорхойлох",
            "Нэмэх болон жагсаах function бичих",
            "JSON файлд хадгалж, дахин унших",
            "Алдаатай input дээр хамгаалалт хийх",
            "README болон demo screenshot бэлтгэх",
        ],
        "skills": ["Python", "Functions", "JSON", "Error handling"],
        "xp": 500,
        "estimated_hours": 4,
    },
    {
        "id": "responsive-profile",
        "course_id": "html",
        "type": "portfolio_project",
        "title": "Responsive Profile Site",
        "subtitle": "Өөрийгөө танилцуулах бодит веб хуудас.",
        "description": "Semantic HTML, CSS layout, responsive breakpoint ашиглан утас болон desktop дээр зөв харагдах profile site бүтээнэ.",
        "steps": [
            "Semantic page skeleton үүсгэх",
            "Typography болон color token сонгох",
            "Grid/flex layout байгуулах",
            "Mobile breakpoint нэмэх",
            "Accessibility checklist шалгах",
        ],
        "skills": ["HTML", "CSS", "Responsive", "Accessibility"],
        "xp": 500,
        "estimated_hours": 3,
    },
]


from learning_experience_extensions import EXTRA_PRACTICE_CHALLENGES, EXTRA_PROJECTS

PRACTICE_CHALLENGES.extend(EXTRA_PRACTICE_CHALLENGES)
PROJECT_CATALOG.extend(EXTRA_PROJECTS)


def get_challenge(challenge_id: str):
    return next((item for item in PRACTICE_CHALLENGES if item["id"] == challenge_id), None)


def get_project(project_id: str):
    return next((item for item in PROJECT_CATALOG if item["id"] == project_id), None)


LEARNING_PATH_NODES = [
    {"id": "path-python-intro", "course_id": "python", "order": 1, "type": "lesson", "title": "Python-ийн суурь", "description": "Source code, variable, data type, list-ийг ойлго.", "href": "/course?id=python", "status": "start"},
    {"id": "path-python-practice", "course_id": "python", "order": 2, "type": "practice", "title": "Python Training Grounds", "description": "Онооны нөхцөл болон функцийн challenge-уудаар чадвараа шалга.", "href": "/practice?course=python", "status": "practice"},
    {"id": "path-python-project", "course_id": "python", "order": 3, "type": "guided_project", "title": "Expense Tracker", "description": "Өгөгдөл, нөхцөл, function ашигласан жижиг бодит app бүтээ.", "href": "/project?id=expense-tracker", "status": "build"},
    {"id": "path-frontend-foundation", "course_id": "frontend", "order": 4, "type": "lesson", "title": "HTML + CSS foundation", "description": "Semantic бүтэц, box model, responsive layout-ийг нэг замд сур.", "href": "/course?id=html", "status": "next"},
    {"id": "path-frontend-practice", "course_id": "frontend", "order": 5, "type": "practice", "title": "Frontend UI Lab", "description": "Semantic card, design token, DOM interaction challenge-уудыг хий.", "href": "/practice?course=html", "status": "practice"},
    {"id": "path-frontend-project", "course_id": "frontend", "order": 6, "type": "portfolio_project", "title": "Interactive Portfolio", "description": "Өөрийн танилцуулгыг responsive, filter-тэй бодит portfolio болго.", "href": "/project?id=frontend-portfolio", "status": "build"},
]
