"""Expanded independent practice challenges and projects.

These are merged with the original catalog so existing IDs and learner data stay
unchanged. Tests are metadata for future database seeding and grader adapters.
"""


def challenge(*, challenge_id, course_id, kind, difficulty, title, hook, description, starter_code, expected_output, hint, xp, lesson_id, tests):
    return {
        "id": challenge_id,
        "course_id": course_id,
        "type": kind,
        "difficulty": difficulty,
        "title": title,
        "hook": hook,
        "description": description,
        "starter_code": starter_code,
        "expected_output": expected_output,
        "hint": hint,
        "xp": xp,
        "lesson_id": lesson_id,
        "tests": tests,
    }


EXTRA_PRACTICE_CHALLENGES = [
    challenge(
        challenge_id="html-semantic-article",
        course_id="html", kind="exercise", difficulty="beginner",
        title="Semantic нийтлэл", hook="Энэ нийтлэлийг browser-д утгатай болго.",
        description="article дотор h1, p, time, footer ашиглан нийтлэлийн бүтэц үүсгэ.",
        starter_code="<div class=\"post\">\n  <!-- Semantic structure энд бич -->\n</div>",
        expected_output="<article>", hint="Гаднах div ямар утгатай хэсгийг илэрхийлж байгааг эхлээд нэрлэ.", xp=90,
        lesson_id="html-semantic-content", tests=[{"input":"", "expected_output":"<article>", "is_hidden":False}, {"input":"", "expected_output":"<time", "is_hidden":True}],
    ),
    challenge(
        challenge_id="html-accessible-image",
        course_id="html", kind="bug_lab", difficulty="beginner",
        title="Alt text bug hunter", hook="Зураг харагдахгүй үед мэдээлэл алга боллоо.",
        description="img element-д descriptive alt нэмээд decorative icon-ийг тусад нь тэмдэглэ.",
        starter_code="<img src=\"speaker.png\">\n<span class=\"icon\">★</span>",
        expected_output="alt=", hint="Зураг хэрэглэгчид ямар мэдээлэл өгч байгааг нэг өгүүлбэрээр бич.", xp=80,
        lesson_id="html-images-media", tests=[{"input":"", "expected_output":"alt=", "is_hidden":False}, {"input":"", "expected_output":"alt=\"\"", "is_hidden":True}],
    ),
    challenge(
        challenge_id="html-navigation",
        course_id="html", kind="exercise", difficulty="beginner",
        title="Сургалтын navigation", hook="Хэрэглэгч дараагийн page-ээ төөрөхгүй олог.",
        description="nav, aria-label, 3 утгатай anchor link бүхий navigation бич.",
        starter_code="<!-- Үндсэн цэсээ энд бич -->", expected_output="<nav", hint="Link-ийн текст өөрөө очих газрын нэр байг.", xp=90,
        lesson_id="html-links-navigation", tests=[{"input":"", "expected_output":"<nav", "is_hidden":False}, {"input":"", "expected_output":"aria-label", "is_hidden":True}],
    ),
    challenge(
        challenge_id="html-form-label",
        course_id="html", kind="exercise", difficulty="beginner",
        title="Label-тай бүртгэлийн form", hook="Form-оо keyboard болон screen reader-д ойлгомжтой болго.",
        description="name, email, password field бүрийг label, id, name, required-тэй үүсгэ.",
        starter_code="<form>\n  <!-- fields энд бич -->\n</form>", expected_output="for=", hint="label for болон input id ижил байх ёстой.", xp=100,
        lesson_id="html-form-labels", tests=[{"input":"", "expected_output":"<label", "is_hidden":False}, {"input":"", "expected_output":"required", "is_hidden":True}],
    ),
    challenge(
        challenge_id="html-button-type-bug",
        course_id="html", kind="bug_lab", difficulty="beginner",
        title="Preview товчны bug", hook="Preview дарахад form санаандгүй submit болж байна.",
        description="Preview button-д зөв type өгч reload болон submit bug-ийг арилга.",
        starter_code="<form>\n  <button id=\"preview\">Preview</button>\n  <button>Хадгалах</button>\n</form>", expected_output="type=\"button\"", hint="Form дотор type-гүй button-ийн default behavior-ийг сана.", xp=80,
        lesson_id="html-form-bug", tests=[{"input":"", "expected_output":"type=\"button\"", "is_hidden":False}],
    ),
    challenge(
        challenge_id="css-box-border",
        course_id="css", kind="exercise", difficulty="beginner",
        title="Border-box card", hook="Card-ийн хэмжээ тогтвортой байг.",
        description="Box sizing, padding, border, margin-ийг зөв тохируул.", starter_code=".card {\n  /* CSS-ээ бич */\n}", expected_output="box-sizing: border-box", hint="Width-д padding, border багтах эсэхийг бод.", xp=90,
        lesson_id="css-box-sizing", tests=[{"input":"", "expected_output":"box-sizing: border-box", "is_hidden":False}, {"input":"", "expected_output":"padding", "is_hidden":True}],
    ),
    challenge(
        challenge_id="css-flex-navbar",
        course_id="css", kind="exercise", difficulty="beginner",
        title="Flex navigation", hook="Navigation item-уудаа нэг хэмнэлтэй байрлуул.",
        description="display:flex, align-items:center, gap:16px, flex-wrap:wrap ашигла.", starter_code=".nav {\n  /* Layout энд бич */\n}", expected_output="display: flex", hint="Layout-ийг child биш parent удирдана.", xp=100,
        lesson_id="css-flexbox", tests=[{"input":"", "expected_output":"display: flex", "is_hidden":False}, {"input":"", "expected_output":"flex-wrap", "is_hidden":True}],
    ),
    challenge(
        challenge_id="css-grid-cards",
        course_id="css", kind="exercise", difficulty="beginner",
        title="Responsive card grid", hook="3 card desktop, 1 card mobile болго.",
        description="auto-fit болон minmax ашиглан fixed breakpoint багатай grid бич.", starter_code=".cards {\n  /* Grid энд бич */\n}", expected_output="minmax", hint="Content-ийн minimum өргөнийг grid-д хэлж өг.", xp=110,
        lesson_id="css-grid", tests=[{"input":"", "expected_output":"display: grid", "is_hidden":False}, {"input":"", "expected_output":"minmax", "is_hidden":True}],
    ),
    challenge(
        challenge_id="css-focus-accessibility",
        course_id="css", kind="exercise", difficulty="intermediate",
        title="Visible focus ring", hook="Keyboard хэрэглэгч одоо хаана байгаагаа мэдэг.",
        description="Button-д :focus-visible outline, outline-offset нэм.", starter_code="button {\n  background: #6b4ce6;\n}\n\n/* Focus state энд */", expected_output="focus-visible", hint="Focus-ийг нуух биш өөрийн тодорхой style өг.", xp=110,
        lesson_id="css-focus-states", tests=[{"input":"", "expected_output":":focus-visible", "is_hidden":False}, {"input":"", "expected_output":"outline", "is_hidden":True}],
    ),
    challenge(
        challenge_id="css-overflow-bug",
        course_id="css", kind="bug_lab", difficulty="intermediate",
        title="Mobile overflow засах", hook="Нарийн дэлгэц дээр page хажуу тийш урсаад байна.",
        description="Fixed width card, image болон flex child-ийн overflow шалтгааныг зас.", starter_code=".layout { width: 1000px; }\n.card { display: flex; }\nimg { width: 600px; }", expected_output="max-width: 100%", hint="Content viewport-оос томрохгүй байх гурван дүрэм бод.", xp=120,
        lesson_id="css-overflow-bug", tests=[{"input":"", "expected_output":"max-width: 100%", "is_hidden":False}, {"input":"", "expected_output":"min-width: 0", "is_hidden":True}],
    ),
    challenge(
        challenge_id="js-function-xp",
        course_id="javascript", kind="exercise", difficulty="beginner",
        title="XP function", hook="Нэг function-ээр reward тооц.",
        description="base XP болон multiplier авч үржвэрийг return хий.", starter_code="function reward(baseXp, multiplier) {\n  // return бич\n}\n\nconsole.log(reward(50, 2));", expected_output="100", hint="Print биш caller-д утга буцаа.", xp=90,
        lesson_id="js-functions-contract", tests=[{"input":"50,2", "expected_output":"100", "is_hidden":False}, {"input":"0,4", "expected_output":"0", "is_hidden":True}],
    ),
    challenge(
        challenge_id="js-array-filter-passed",
        course_id="javascript", kind="exercise", difficulty="beginner",
        title="Passed lessons filter", hook="Дууссан хичээлүүдийг ялга.",
        description="lessons array-аас completed=true item-уудыг filter ашиглан гарга.", starter_code="const lessons = [\n  {title: 'HTML', completed: true},\n  {title: 'CSS', completed: false}\n];\nconst passed = [];\nconsole.log(passed.length);", expected_output="1", hint="filter callback-д boolean expression буцаа.", xp=100,
        lesson_id="js-array-methods", tests=[{"input":"", "expected_output":"1", "is_hidden":False}, {"input":"", "expected_output":"filter", "is_hidden":True}],
    ),
    challenge(
        challenge_id="js-safe-dom",
        course_id="javascript", kind="exercise", difficulty="beginner",
        title="Safe DOM update", hook="User text-ийг аюулгүйгээр page-д харуул.",
        description="Input-ийн утгыг textContent-оор output element-д оруул.", starter_code="const input = document.querySelector('#name');\nconst output = document.querySelector('#output');\n\n// Нэрийг аюулгүй харуул", expected_output="textContent", hint="User data-г HTML гэж задлахгүй байх property сонго.", xp=100,
        lesson_id="js-dom-query", tests=[{"input":"", "expected_output":"textContent", "is_hidden":False}, {"input":"", "expected_output":"querySelector", "is_hidden":True}],
    ),
    challenge(
        challenge_id="js-json-error",
        course_id="javascript", kind="bug_lab", difficulty="intermediate",
        title="HTML-as-JSON bug", hook="Server error үед page crash болохгүй байг.",
        description="response.json()-г шууд дуудахгүй text уншаад parse error-ийг ойлгомжтой болго.", starter_code="fetch('/api/progress')\n  .then(response => response.json())\n  .then(data => console.log(data));", expected_output="response.text()", hint="Server JSON биш HTML буцааж болохыг тооц.", xp=130,
        lesson_id="js-fetch-json", tests=[{"input":"", "expected_output":"response.text()", "is_hidden":False}, {"input":"", "expected_output":"JSON.parse", "is_hidden":True}],
    ),
    challenge(
        challenge_id="js-state-render",
        course_id="javascript", kind="exercise", difficulty="intermediate",
        title="Single source of truth", hook="Counter state-ээ нэг газраас удирд.",
        description="State object, render function, click action гэсэн бүтэцтэй counter хий.", starter_code="const state = {count: 0};\nfunction render() {\n  // output шинэчил\n}\n\n// action энд", expected_output="render", hint="Action state өөрчилнө, render UI-г шинэчилнэ.", xp=120,
        lesson_id="js-state-render", tests=[{"input":"", "expected_output":"render()", "is_hidden":False}, {"input":"", "expected_output":"state.count", "is_hidden":True}],
    ),
    challenge(
        challenge_id="py-function-return",
        course_id="python", kind="exercise", difficulty="beginner",
        title="Нийт дүнгийн function", hook="Тооцооллоо дахин ашиглагддаг болго.",
        description="price, quantity авч нийт дүнг return хийдэг function бич.", starter_code="def total(price, quantity):\n    # Тооцоолоод return хий\n    pass\n\nprint(total(1200, 3))", expected_output="3600", hint="price * quantity-г caller-д буцаа.", xp=90,
        lesson_id="py-functions", tests=[{"input":"1200,3", "expected_output":"3600", "is_hidden":False}, {"input":"0,8", "expected_output":"0", "is_hidden":True}],
    ),
    challenge(
        challenge_id="py-dict-score",
        course_id="python", kind="exercise", difficulty="beginner",
        title="Profile XP update", hook="Dictionary data-г нэрээр нь шинэчил.",
        description="student dictionary-ийн XP-г 50-аар нэмээд name болон xp хэвлэ.", starter_code="student = {'name': 'Ану', 'xp': 120}\n# XP update энд\nprint(student['name'], student['xp'])", expected_output="170", hint="Key ашиглан existing value дээр нэм.", xp=90,
        lesson_id="py-dictionaries", tests=[{"input":"", "expected_output":"170", "is_hidden":False}, {"input":"", "expected_output":"Ану", "is_hidden":True}],
    ),
    challenge(
        challenge_id="py-list-comprehension",
        course_id="python", kind="exercise", difficulty="intermediate",
        title="Тэнцсэн сурагчид", hook="Data-г нэг бүрчлэн бодож шүү.",
        description="Students list-ээс score >= 60 нэрүүдийг comprehension эсвэл loop-оор гарга.", starter_code="students = [{'name': 'Ану', 'score': 85}, {'name': 'Бат', 'score': 45}]\npassed = []\nprint(passed)", expected_output="Ану", hint="Нэрийг авахын өмнө score boundary-г шалга.", xp=110,
        lesson_id="py-comprehension", tests=[{"input":"", "expected_output":"Ану", "is_hidden":False}, {"input":"", "expected_output":"Бат", "is_hidden":True}],
    ),
    challenge(
        challenge_id="py-json-save",
        course_id="python", kind="exercise", difficulty="intermediate",
        title="Progress JSON хадгалах", hook="Програм хаагдсан ч progress үлддэг болго.",
        description="Progress dictionary-г ensure_ascii=False, indent=2 ашиглан JSON файлд бич.", starter_code="import json\nprogress = {'course': 'HTML', 'percent': 40}\n# JSON хадгал", expected_output="json.dump", hint="File-ээ utf-8 encoding-тэй нээ.", xp=120,
        lesson_id="py-json", tests=[{"input":"", "expected_output":"json.dump", "is_hidden":False}, {"input":"", "expected_output":"ensure_ascii=False", "is_hidden":True}],
    ),
    challenge(
        challenge_id="py-traceback-bug",
        course_id="python", kind="bug_lab", difficulty="intermediate",
        title="Traceback уншигч", hook="0-оор хуваах bug-ийг user-friendly зас.",
        description="count=0 үед ZeroDivisionError гаргахын оронд тодорхой ValueError өг.", starter_code="def average(total, count):\n    return total / count\n\nprint(average(10, 0))", expected_output="ValueError", hint="Invalid input-ийг division-ээс өмнө шалга.", xp=130,
        lesson_id="py-traceback", tests=[{"input":"", "expected_output":"ValueError", "is_hidden":False}, {"input":"", "expected_output":"count", "is_hidden":True}],
    ),
]


EXTRA_PROJECTS = [
    {
        "id": "interactive-course-dashboard",
        "course_id": "javascript",
        "type": "portfolio_project",
        "title": "Interactive Course Dashboard",
        "subtitle": "Суралцагчийн өөрийн ахицын dashboard.",
        "description": "HTML semantic structure, CSS responsive layout, JavaScript state/API ашиглан course progress, filter, loading/error state бүхий dashboard бүтээнэ.",
        "steps": [
            "State model болон loading/error/empty төлөв зурах",
            "Semantic dashboard markup үүсгэх",
            "Responsive card/grid layout хийх",
            "Filter болон completion interaction нэмэх",
            "API adapter, safe DOM rendering, README бэлтгэх",
        ],
        "skills": ["HTML", "CSS", "JavaScript", "DOM", "API", "Accessibility"],
        "xp": 650,
        "estimated_hours": 6,
    },
    {
        "id": "learning-tracker-cli",
        "course_id": "python",
        "type": "portfolio_project",
        "title": "Personal Learning Tracker CLI",
        "subtitle": "Өөрийн хичээл, XP, streak-ээ terminal-аас удирд.",
        "description": "Python function, dictionary/list, JSON persistence, exception handling, modules болон tests ашиглан learning tracker CLI бүтээнэ.",
        "steps": [
            "Lesson болон progress data model тодорхойлох",
            "Нэмэх, дуусгах, жагсаах command бичих",
            "JSON storage adapter хийх",
            "Invalid input болон missing file хамгаалах",
            "Test, README, demo transcript бэлтгэх",
        ],
        "skills": ["Python", "Functions", "JSON", "Modules", "Errors", "Testing"],
        "xp": 650,
        "estimated_hours": 6,
    },
    {
        "id": "mongolian-event-site",
        "course_id": "html",
        "type": "portfolio_project",
        "title": "Монгол Tech Event Site",
        "subtitle": "Semantic, accessible, responsive event website.",
        "description": "Монгол хэлний tech event-ийн schedule, speaker, location, registration form бүхий олон section-тэй website бүтээнэ.",
        "steps": [
            "User ба event content outline гаргах",
            "Semantic landmarks болон heading hierarchy хийх",
            "Speaker/media хэсэг нэмэх",
            "Accessible registration form хийх",
            "Keyboard, zoom, alt, link purpose checklist ажиллуулах",
        ],
        "skills": ["HTML", "Semantic HTML", "Forms", "Accessibility", "Content design"],
        "xp": 550,
        "estimated_hours": 5,
    },
    {
        "id": "responsive-design-system",
        "course_id": "css",
        "type": "guided_project",
        "title": "Responsive Design System",
        "subtitle": "Token, component, layout-аар жижиг UI system байгуул.",
        "description": "Color/type/spacing token, button/card states, Flexbox/Grid болон mobile-first breakpoint ашиглан дахин ашиглах UI system бүтээнэ.",
        "steps": [
            "Design token table гаргах",
            "Button, card, badge component хийх",
            "Dashboard layout-ийг Grid/Flexbox-оор хийх",
            "Focus, reduced-motion, contrast review хийх",
            "CSS architecture refactor болон component gallery гаргах",
        ],
        "skills": ["CSS", "Design tokens", "Flexbox", "Grid", "Responsive", "Accessibility"],
        "xp": 550,
        "estimated_hours": 5,
    },
]
