-- Codehaven learning-platform schema migration.
-- Apply after 001_auth_roles.sql.
-- This migration is idempotent and creates the tables required by the Flask APIs.

create table if not exists public.courses (
    id bigint generated by default as identity primary key,
    title text not null,
    description text not null default '',
    created_by bigint references public.users(id) on delete set null,
    is_published boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.modules (
    id bigint generated by default as identity primary key,
    course_id bigint not null references public.courses(id) on delete cascade,
    title text not null,
    description text not null default '',
    position integer not null default 1,
    status text not null default 'published' check (status in ('draft', 'published', 'archived')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (course_id, position)
);

create table if not exists public.lessons (
    id bigint generated by default as identity primary key,
    module_id bigint not null references public.modules(id) on delete cascade,
    title text not null,
    content text not null default '',
    position integer not null default 1,
    estimated_minutes integer not null default 15 check (estimated_minutes > 0),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (module_id, position)
);

create table if not exists public.classes (
    id bigint generated by default as identity primary key,
    course_id bigint not null references public.courses(id) on delete cascade,
    teacher_id bigint not null references public.users(id) on delete restrict,
    name text not null,
    enrollment_code text not null unique,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.enrollments (
    id bigint generated by default as identity primary key,
    class_id bigint not null references public.classes(id) on delete cascade,
    user_id bigint not null references public.users(id) on delete cascade,
    enrollment_role text not null default 'student' check (enrollment_role in ('student', 'teacher')),
    joined_at timestamptz not null default now(),
    unique (class_id, user_id)
);

create table if not exists public.skills (
    id bigint generated by default as identity primary key,
    name text not null unique,
    description text not null default '',
    category text,
    created_at timestamptz not null default now()
);

create table if not exists public.learning_objectives (
    id bigint generated by default as identity primary key,
    course_id bigint references public.courses(id) on delete cascade,
    module_id bigint references public.modules(id) on delete cascade,
    skill_id bigint references public.skills(id) on delete set null,
    title text not null,
    description text not null default '',
    position integer not null default 1,
    created_at timestamptz not null default now()
);

create table if not exists public.problems (
    id bigint generated by default as identity primary key,
    title text not null,
    description text not null default '',
    difficulty text not null check (difficulty in ('easy', 'medium', 'hard')),
    starter_code text not null default '',
    explanation text not null default '',
    language text not null default 'python',
    created_by bigint references public.users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.test_cases (
    id bigint generated by default as identity primary key,
    problem_id bigint not null references public.problems(id) on delete cascade,
    input text not null default '',
    expected_output text not null default '',
    is_hidden boolean not null default false,
    created_at timestamptz not null default now()
);

create table if not exists public.hints (
    id bigint generated by default as identity primary key,
    problem_id bigint not null references public.problems(id) on delete cascade,
    level integer not null check (level > 0),
    content text not null,
    created_at timestamptz not null default now(),
    unique (problem_id, level)
);

create table if not exists public.problem_versions (
    id bigint generated by default as identity primary key,
    problem_id bigint not null references public.problems(id) on delete cascade,
    version_number integer not null check (version_number > 0),
    content_hash text not null,
    created_at timestamptz not null default now(),
    unique (problem_id, version_number)
);

create table if not exists public.problem_skills (
    problem_id bigint not null references public.problems(id) on delete cascade,
    skill_id bigint not null references public.skills(id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (problem_id, skill_id)
);

create table if not exists public.assignments (
    id bigint generated by default as identity primary key,
    class_id bigint references public.classes(id) on delete cascade,
    title text not null,
    description text not null default '',
    due_at timestamptz,
    created_by bigint references public.users(id) on delete set null,
    created_at timestamptz not null default now()
);

create table if not exists public.exams (
    id bigint generated by default as identity primary key,
    class_id bigint references public.classes(id) on delete cascade,
    title text not null,
    description text not null default '',
    starts_at timestamptz,
    ends_at timestamptz,
    created_by bigint references public.users(id) on delete set null,
    created_at timestamptz not null default now()
);

create table if not exists public.exam_problems (
    exam_id bigint not null references public.exams(id) on delete cascade,
    problem_id bigint not null references public.problems(id) on delete cascade,
    position integer not null default 1,
    points numeric(6, 2) not null default 1,
    primary key (exam_id, problem_id)
);

create table if not exists public.submissions (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    problem_id bigint not null references public.problems(id) on delete restrict,
    assignment_id bigint references public.assignments(id) on delete set null,
    exam_id bigint references public.exams(id) on delete set null,
    code text not null,
    status text not null default 'pending' check (status in ('pending', 'running', 'accepted', 'partial_accepted', 'rejected', 'error')),
    score numeric(6, 2) not null default 0 check (score >= 0 and score <= 100),
    evaluated_at timestamptz,
    created_at timestamptz not null default now()
);

create table if not exists public.submission_results (
    id bigint generated by default as identity primary key,
    submission_id bigint not null references public.submissions(id) on delete cascade,
    test_number integer not null,
    status text not null default 'pending',
    passed boolean not null default false,
    actual_output text,
    expected_output text,
    error text,
    is_hidden boolean not null default false,
    created_at timestamptz not null default now(),
    unique (submission_id, test_number)
);

create table if not exists public.teacher_feedback (
    id bigint generated by default as identity primary key,
    submission_id bigint not null references public.submissions(id) on delete cascade,
    teacher_id bigint not null references public.users(id) on delete restrict,
    feedback text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.exam_submissions (
    id bigint generated by default as identity primary key,
    exam_id bigint not null references public.exams(id) on delete cascade,
    user_id bigint not null references public.users(id) on delete cascade,
    status text not null default 'in_progress' check (status in ('in_progress', 'submitted', 'graded')),
    score numeric(6, 2) not null default 0 check (score >= 0 and score <= 100),
    started_at timestamptz not null default now(),
    submitted_at timestamptz,
    unique (exam_id, user_id)
);

create table if not exists public.mastery_snapshots (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    skill_id bigint not null references public.skills(id) on delete cascade,
    mastery_score numeric(6, 2) not null default 0 check (mastery_score >= 0 and mastery_score <= 100),
    first_attempt_success_rate numeric(6, 2),
    retry_recovery_rate numeric(6, 2),
    hint_usage_count integer not null default 0 check (hint_usage_count >= 0),
    updated_at timestamptz not null default now(),
    unique (user_id, skill_id)
);

create index if not exists courses_created_by_idx on public.courses (created_by);
create index if not exists modules_course_position_idx on public.modules (course_id, position);
create index if not exists lessons_module_position_idx on public.lessons (module_id, position);
create index if not exists classes_teacher_idx on public.classes (teacher_id);
create index if not exists enrollments_user_idx on public.enrollments (user_id);
create index if not exists problems_difficulty_idx on public.problems (difficulty);
create index if not exists test_cases_problem_idx on public.test_cases (problem_id, is_hidden);
create index if not exists submissions_user_created_idx on public.submissions (user_id, created_at desc);
create index if not exists submissions_problem_idx on public.submissions (problem_id);
create index if not exists submission_results_submission_idx on public.submission_results (submission_id);
create index if not exists mastery_user_idx on public.mastery_snapshots (user_id);
create index if not exists mastery_skill_idx on public.mastery_snapshots (skill_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists courses_set_updated_at on public.courses;
create trigger courses_set_updated_at before update on public.courses
for each row execute function public.set_updated_at();

drop trigger if exists modules_set_updated_at on public.modules;
create trigger modules_set_updated_at before update on public.modules
for each row execute function public.set_updated_at();

drop trigger if exists lessons_set_updated_at on public.lessons;
create trigger lessons_set_updated_at before update on public.lessons
for each row execute function public.set_updated_at();

drop trigger if exists classes_set_updated_at on public.classes;
create trigger classes_set_updated_at before update on public.classes
for each row execute function public.set_updated_at();

drop trigger if exists problems_set_updated_at on public.problems;
create trigger problems_set_updated_at before update on public.problems
for each row execute function public.set_updated_at();

comment on table public.courses is 'Learning paths managed by teachers and administrators.';
comment on table public.problems is 'Practice problems and assessment coding prompts.';
comment on table public.submissions is 'Student code submissions and evaluator status.';
comment on table public.mastery_snapshots is 'Per-user skill mastery state used by analytics dashboards.';
