-- Persistent lesson completion records for the authenticated learning workspace.
-- Apply after 002_learning_platform.sql.

create table if not exists public.lesson_progress (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    lesson_id bigint not null references public.lessons(id) on delete cascade,
    status text not null default 'in_progress' check (status in ('in_progress', 'completed')),
    started_at timestamptz not null default now(),
    completed_at timestamptz,
    unique (user_id, lesson_id)
);

create index if not exists lesson_progress_user_idx on public.lesson_progress (user_id, started_at desc);

alter table public.lesson_progress add column if not exists status text not null default 'completed';
alter table public.lesson_progress add column if not exists started_at timestamptz not null default now();

update public.lesson_progress set status = 'completed' where completed_at is not null;
