-- Persistent lesson completion records for the authenticated learning workspace.
-- Apply after 002_learning_platform.sql.

create table if not exists public.lesson_progress (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    lesson_id bigint not null references public.lessons(id) on delete cascade,
    completed_at timestamptz not null default now(),
    unique (user_id, lesson_id)
);

create index if not exists lesson_progress_user_idx on public.lesson_progress (user_id, completed_at desc);
