-- Codehaven assessment and learner progress extension.
-- Safe to run after 001_auth_roles.sql through 004_learning_progress.sql.

alter table if exists public.exams
    add column if not exists duration_minutes integer not null default 20,
    add column if not exists max_attempts integer not null default 3,
    add column if not exists status text not null default 'published',
    add column if not exists updated_at timestamptz not null default now();

create table if not exists public.exam_questions (
    id bigint generated by default as identity primary key,
    exam_id bigint not null references public.exams(id) on delete cascade,
    problem_id bigint references public.problems(id) on delete set null,
    position integer not null default 1,
    question_type text not null default 'multiple_choice' check (question_type in ('multiple_choice', 'short_answer', 'code')),
    prompt text not null,
    options jsonb not null default '[]'::jsonb,
    correct_answer text,
    points numeric(8, 2) not null default 1 check (points > 0),
    explanation text not null default '',
    created_at timestamptz not null default now(),
    unique (exam_id, position)
);

create table if not exists public.exam_attempts (
    id bigint generated by default as identity primary key,
    exam_id bigint not null references public.exams(id) on delete cascade,
    user_id bigint not null references public.users(id) on delete cascade,
    status text not null default 'in_progress' check (status in ('in_progress', 'submitted', 'graded', 'expired')),
    score numeric(8, 2) not null default 0 check (score >= 0 and score <= 100),
    earned_points numeric(10, 2) not null default 0,
    total_points numeric(10, 2) not null default 0,
    started_at timestamptz not null default now(),
    submitted_at timestamptz,
    graded_at timestamptz,
    unique (exam_id, user_id, id)
);

create table if not exists public.exam_answers (
    id bigint generated by default as identity primary key,
    attempt_id bigint not null references public.exam_attempts(id) on delete cascade,
    question_id bigint not null references public.exam_questions(id) on delete cascade,
    answer text not null default '',
    is_correct boolean,
    earned_points numeric(10, 2) not null default 0,
    feedback text not null default '',
    updated_at timestamptz not null default now(),
    unique (attempt_id, question_id)
);

create index if not exists exams_status_idx on public.exams (status, starts_at, ends_at);
create index if not exists exam_questions_exam_position_idx on public.exam_questions (exam_id, position);
create index if not exists exam_attempts_user_status_idx on public.exam_attempts (user_id, status, started_at desc);
create index if not exists exam_attempts_exam_idx on public.exam_attempts (exam_id, submitted_at desc);
create index if not exists exam_answers_attempt_idx on public.exam_answers (attempt_id);

create or replace function public.set_exam_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists exams_updated_at on public.exams;
create trigger exams_updated_at
before update on public.exams
for each row execute function public.set_exam_updated_at();
