-- Server-side gamification state. Apply after 002_learning_platform.sql.

create table if not exists public.gamification_profiles (
    user_id bigint primary key references public.users(id) on delete cascade,
    total_xp integer not null default 0 check (total_xp >= 0),
    level integer not null default 1 check (level >= 1),
    current_streak integer not null default 0 check (current_streak >= 0),
    longest_streak integer not null default 0 check (longest_streak >= 0),
    last_activity_date date,
    updated_at timestamptz not null default now()
);

create table if not exists public.xp_events (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    event_key text not null,
    event_type text not null,
    source_id bigint,
    xp_amount integer not null check (xp_amount > 0),
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    unique (user_id, event_key)
);

create table if not exists public.learning_streaks (
    user_id bigint not null references public.users(id) on delete cascade,
    activity_date date not null,
    source_type text not null,
    source_id bigint,
    created_at timestamptz not null default now(),
    primary key (user_id, activity_date)
);

create table if not exists public.badges (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    title text not null,
    description text not null default '',
    condition_type text not null,
    condition_value integer not null default 1,
    xp_reward integer not null default 0 check (xp_reward >= 0),
    created_at timestamptz not null default now()
);

create table if not exists public.user_badges (
    user_id bigint not null references public.users(id) on delete cascade,
    badge_id bigint not null references public.badges(id) on delete cascade,
    earned_at timestamptz not null default now(),
    primary key (user_id, badge_id)
);

create index if not exists xp_events_user_created_idx on public.xp_events (user_id, created_at desc);
create index if not exists learning_streaks_user_date_idx on public.learning_streaks (user_id, activity_date desc);

insert into public.badges (slug, title, description, condition_type, condition_value, xp_reward)
values
    ('first-accepted', 'Эхний ялалт', 'Анхны challenge-ээ амжилттай дуусгасан.', 'accepted_submissions', 1, 25),
    ('streak-3', '3 өдрийн хэмнэл', 'Гурван өдөр дараалан суралцсан.', 'streak_days', 3, 40),
    ('streak-7', '7 өдрийн хэмнэл', 'Долоон өдөр дараалан суралцсан.', 'streak_days', 7, 100),
    ('bug-hunter', 'Bug Hunter', 'Гурван bug lab зассан.', 'bug_labs', 3, 80),
    ('xp-1000', '1000 XP', 'Нийт 1000 XP цуглуулсан.', 'total_xp', 1000, 100)
on conflict (slug) do nothing;
