-- Persist learner attempts for static and published catalog challenges.
-- Applies after 006_local_app_auth.sql; Supabase remains database-only.

create table if not exists public.catalog_challenge_attempts (
    id bigint generated by default as identity primary key,
    app_user_id uuid not null references public.app_auth_identities(id) on delete cascade,
    challenge_id text not null,
    language text not null check (language in ('python', 'javascript', 'html', 'css')),
    code text not null,
    status text not null check (status in ('accepted', 'partial_accepted', 'wrong_answer', 'error')),
    total_tests integer not null default 0 check (total_tests >= 0),
    passed_tests integer not null default 0 check (passed_tests >= 0),
    results jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists catalog_attempts_user_created_idx
    on public.catalog_challenge_attempts (app_user_id, created_at desc);
create index if not exists catalog_attempts_challenge_idx
    on public.catalog_challenge_attempts (challenge_id, created_at desc);
