-- Canonical Supabase identity and learner-owned state. Apply to a clean project
-- before loading application content. This migration is safe to re-run.
create extension if not exists pgcrypto;

-- Compatibility projection for the existing Flask RBAC/domain APIs. Authentication
-- remains owned by auth.users; no password is stored in this table.
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique references auth.users(id) on delete cascade,
  email text not null unique,
  name text not null,
  role text not null default 'student' check (role in ('student', 'teacher', 'admin', 'owner')),
  requested_role text check (requested_role is null or requested_role = 'teacher'),
  teacher_approval_status text not null default 'approved'
    check (teacher_approval_status in ('pending', 'approved', 'rejected')),
  auth_provider text check (auth_provider is null or auth_provider in ('email', 'google')),
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists users_auth_user_id_idx on public.users(auth_user_id);
create index if not exists users_teacher_request_idx
  on public.users(requested_role, teacher_approval_status);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  role text not null default 'student' check (role in ('student', 'teacher', 'admin', 'owner')),
  locale text not null default 'mn' check (locale in ('mn', 'en')),
  theme text not null default 'system' check (theme in ('light', 'dark', 'system')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.course_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  course_slug text not null check (course_slug in ('python', 'html', 'css', 'javascript')),
  progress_percent smallint not null default 0 check (progress_percent between 0 and 100),
  updated_at timestamptz not null default now(),
  primary key (user_id, course_slug)
);

create table if not exists public.lesson_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  course_slug text not null check (course_slug in ('python', 'html', 'css', 'javascript')),
  lesson_slug text not null check (char_length(lesson_slug) between 1 and 96),
  completed_at timestamptz not null default now(),
  primary key (user_id, course_slug, lesson_slug)
);

create table if not exists public.quiz_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  course_slug text not null check (course_slug in ('python', 'html', 'css', 'javascript')),
  lesson_slug text not null check (char_length(lesson_slug) between 1 and 96),
  score integer not null check (score >= 0),
  total_questions integer not null check (total_questions > 0 and score <= total_questions),
  answers jsonb not null default '[]'::jsonb,
  submitted_at timestamptz not null default now()
);

create index if not exists course_progress_user_idx on public.course_progress(user_id, updated_at desc);
create index if not exists lesson_progress_user_idx on public.lesson_progress(user_id, completed_at desc);
create index if not exists quiz_attempts_user_idx on public.quiz_attempts(user_id, submitted_at desc);

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create or replace function private.set_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function private.set_updated_at();
drop trigger if exists course_progress_set_updated_at on public.course_progress;
create trigger course_progress_set_updated_at before update on public.course_progress
for each row execute function private.set_updated_at();

create or replace function private.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email, display_name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;
revoke all on function private.handle_new_user() from public, anon, authenticated;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function private.handle_new_user();

alter table public.profiles enable row level security;
alter table public.course_progress enable row level security;
alter table public.lesson_progress enable row level security;
alter table public.quiz_attempts enable row level security;

drop policy if exists profile_select_own on public.profiles;
create policy profile_select_own on public.profiles for select to authenticated using ((select auth.uid()) = id);
drop policy if exists profile_update_own on public.profiles;
create policy profile_update_own on public.profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);
drop policy if exists profile_insert_own on public.profiles;
create policy profile_insert_own on public.profiles for insert to authenticated with check ((select auth.uid()) = id);

-- Column privileges prevent direct API role escalation even though a user owns its row.
revoke update (role, id, email) on public.profiles from authenticated;
grant select, insert, update (display_name, locale, theme) on public.profiles to authenticated;
grant select, insert, update, delete on public.course_progress, public.lesson_progress, public.quiz_attempts to authenticated;

do $$
declare t text;
begin
  foreach t in array array['course_progress', 'lesson_progress', 'quiz_attempts'] loop
    execute format('drop policy if exists %I on public.%I', t || '_own_select', t);
    execute format('create policy %I on public.%I for select to authenticated using ((select auth.uid()) = user_id)', t || '_own_select', t);
    execute format('drop policy if exists %I on public.%I', t || '_own_insert', t);
    execute format('create policy %I on public.%I for insert to authenticated with check ((select auth.uid()) = user_id)', t || '_own_insert', t);
    execute format('drop policy if exists %I on public.%I', t || '_own_update', t);
    execute format('create policy %I on public.%I for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id)', t || '_own_update', t);
  end loop;
end $$;
drop policy if exists lesson_progress_own_delete on public.lesson_progress;
create policy lesson_progress_own_delete on public.lesson_progress for delete to authenticated using ((select auth.uid()) = user_id);

do $$ begin alter publication supabase_realtime add table public.course_progress; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.lesson_progress; exception when duplicate_object then null; end $$;

-- Tables without a direct-client policy are intentionally server-only. Flask
-- uses the service role after performing its own resource and role checks.
do $$
declare relation record;
begin
  for relation in
    select schemaname, tablename from pg_tables
    where schemaname = 'public' and tableowner = current_user
  loop
    execute format('alter table %I.%I enable row level security', relation.schemaname, relation.tablename);
  end loop;
end $$;
